/**
 * 영어 문항의 한국어 뜻 — 낱말은 가장 흔한 뜻 하나, 문장은 자연스러운 해석 한 줄.
 *
 * 🔴 이 파일은 **손으로 고치지 말고 다시 만들어라**. 만드는 법은 `scripts/en/make-glossary.mjs`.
 *    웹 브릿지(gpt-web)로 받아 «기계로 거른» 결과다 — 커버리지·한글 포함·길이·원문 일치를 전수 검사한다.
 * 🔴 본 번들에 넣지 않는다. 결과 화면이 **영어 기록을 열 때만** 동적 import 로 불러온다
 *    (2,182줄이라 국어만 쓰는 교실의 첫 로딩을 무겁게 할 이유가 없다).
 *
 * 마지막 갱신 2026-09-14 · 2182개
 */
export const GLOSSARY_EN: Record<string, string> = {
  "cat": "고양이",
  "hat": "모자",
  "bag": "가방",
  "map": "지도",
  "cap": "모자",
  "fan": "선풍기",
  "bat": "방망이",
  "jam": "잼",
  "man": "남자",
  "sad": "슬픈",
  "big": "큰",
  "sit": "앉다",
  "six": "여섯",
  "fish": "물고기",
  "pig": "돼지",
  "hill": "언덕",
  "milk": "우유",
  "pink": "분홍색",
  "wind": "바람",
  "swim": "수영하다",
  "hot": "더운",
  "dog": "개",
  "box": "상자",
  "fox": "여우",
  "pot": "냄비",
  "mom": "엄마",
  "top": "맨 위",
  "shop": "가게",
  "stop": "멈추다",
  "rock": "바위",
  "bus": "버스",
  "sun": "해",
  "cup": "컵",
  "run": "달리다",
  "duck": "오리",
  "jump": "뛰다",
  "truck": "트럭",
  "lunch": "점심",
  "mud": "진흙",
  "hut": "오두막",
  "red": "빨간색",
  "yes": "네",
  "get": "얻다",
  "help": "돕다",
  "best": "가장 좋은",
  "rest": "쉬다",
  "left": "왼쪽",
  "next": "다음",
  "well": "잘",
  "tell": "말하다",
  "blue": "파란색",
  "green": "초록색",
  "yellow": "노란색",
  "orange": "주황색",
  "purple": "보라색",
  "brown": "갈색",
  "black": "검은색",
  "white": "흰색",
  "one": "하나",
  "two": "둘",
  "three": "셋",
  "four": "넷",
  "five": "다섯",
  "seven": "일곱",
  "eight": "여덟",
  "nine": "아홉",
  "ten": "열",
  "cow": "소",
  "horse": "말",
  "sheep": "양",
  "rabbit": "토끼",
  "mouse": "쥐",
  "bird": "새",
  "apple": "사과",
  "cake": "케이크",
  "rice": "밥",
  "egg": "달걀",
  "bread": "빵",
  "soup": "수프",
  "tea": "차",
  "water": "물",
  "pen": "펜",
  "book": "책",
  "desk": "책상",
  "ruler": "자",
  "pencil": "연필",
  "eraser": "지우개",
  "board": "칠판",
  "chair": "의자",
  "Hello, Jane!": "안녕, 제인!",
  "Good morning.": "좋은 아침이에요.",
  "Hi, Sam.": "안녕, 샘.",
  "Nice to meet you.": "만나서 반가워요.",
  "Good afternoon.": "안녕하세요.",
  "See you later.": "나중에 봐요.",
  "Good night, Mom.": "엄마, 안녕히 주무세요.",
  "Have a good day.": "좋은 하루 보내세요.",
  "Bye, see you.": "안녕, 또 봐요.",
  "How do you do?": "안녕하세요?",
  "I am hot.": "나는 더워요.",
  "I am cold.": "나는 추워요.",
  "I am ready for fall.": "나는 가을을 맞을 준비가 됐어요.",
  "I am warm.": "나는 따뜻해요.",
  "I am happy in spring.": "나는 봄에 행복해요.",
  "I am cool.": "나는 시원해요.",
  "I am outside.": "나는 밖에 있어요.",
  "I am in the snow.": "나는 눈 속에 있어요.",
  "I am under a tree.": "나는 나무 아래에 있어요.",
  "I am glad.": "나는 기뻐요.",
  "It is a cap.": "그것은 모자예요.",
  "It is my hat.": "그것은 내 모자예요.",
  "It is a shirt.": "그것은 셔츠예요.",
  "It is your coat.": "그것은 네 외투예요.",
  "It is a skirt.": "그것은 치마예요.",
  "It is my dress.": "그것은 내 원피스예요.",
  "It is a sock.": "그것은 양말이에요.",
  "It is your shoe.": "그것은 네 신발이에요.",
  "It is a jacket.": "그것은 재킷이에요.",
  "It is my glove.": "그것은 내 장갑이에요.",
  "Who is he?": "그 남자아이는 누구예요?",
  "Who is she?": "그 여자아이는 누구예요?",
  "Is he your dad?": "그분은 네 아빠니?",
  "Is she your mom?": "그분은 네 엄마니?",
  "Is he your brother?": "그 아이는 네 남자 형제니?",
  "Is she your sister?": "그 아이는 네 여자 형제니?",
  "Is this your family?": "이분들이 네 가족이니?",
  "Is that your baby?": "저 아기가 네 아기니?",
  "Who is your mom?": "누가 네 엄마니?",
  "Who is your dad?": "누가 네 아빠니?",
  "Yes, I do.": "네, 그래요.",
  "No, I don't.": "아니요, 그렇지 않아요.",
  "Yes, I can.": "네, 할 수 있어요.",
  "No, I can't.": "아니요, 할 수 없어요.",
  "I like soccer.": "나는 축구를 좋아해요.",
  "I play baseball.": "나는 야구를 해요.",
  "I can swim.": "나는 수영할 수 있어요.",
  "I like tennis.": "나는 테니스를 좋아해요.",
  "I play basketball.": "나는 농구를 해요.",
  "I can run fast.": "나는 빨리 달릴 수 있어요.",
  "dad": "아빠",
  "can": "할 수 있다",
  "van": "승합차",
  "pan": "프라이팬",
  "ant": "개미",
  "flag": "깃발",
  "lamp": "등",
  "math": "수학",
  "happy": "행복한",
  "kid": "아이",
  "him": "그를",
  "his": "그의",
  "win": "이기다",
  "hit": "치다",
  "lip": "입술",
  "gift": "선물",
  "sing": "노래하다",
  "kick": "차다",
  "sick": "아픈",
  "job": "일",
  "not": "아니다",
  "lot": "많음",
  "hop": "깡충 뛰다",
  "jog": "천천히 달리다",
  "doll": "인형",
  "golf": "골프",
  "song": "노래",
  "pond": "연못",
  "block": "블록",
  "fun": "재미",
  "drum": "북",
  "club": "동아리",
  "luck": "운",
  "hug": "안다",
  "gum": "껌",
  "nut": "견과",
  "but": "하지만",
  "rub": "문지르다",
  "sum": "합",
  "hen": "암탉",
  "pet": "반려동물",
  "leg": "다리",
  "bed": "침대",
  "net": "그물",
  "wet": "젖은",
  "men": "남자들",
  "My cap is red.": "내 모자는 빨간색이에요.",
  "This bag is blue.": "이 가방은 파란색이에요.",
  "Her hat is pink.": "그녀의 모자는 분홍색이에요.",
  "That cup is green.": "저 컵은 초록색이에요.",
  "Your pen is black.": "네 펜은 검은색이에요.",
  "His box is white.": "그의 상자는 흰색이에요.",
  "The bus is yellow.": "그 버스는 노란색이에요.",
  "A kite is purple.": "연은 보라색이에요.",
  "These socks are gray.": "이 양말들은 회색이에요.",
  "Those shoes are brown.": "저 신발들은 갈색이에요.",
  "I see four ducks.": "오리 네 마리가 보여요.",
  "We have two cats.": "우리는 고양이 두 마리가 있어요.",
  "Five birds can fly.": "새 다섯 마리가 날 수 있어요.",
  "Count the six stars.": "별 여섯 개를 세어 보세요.",
  "There are ten balls.": "공이 열 개 있어요.",
  "She has three dolls.": "그 아이는 인형 세 개가 있어요.",
  "He sees seven fish.": "그 아이는 물고기 일곱 마리를 봐요.",
  "Nine frogs jump.": "개구리 아홉 마리가 뛰어요.",
  "Eight ants walk.": "개미 여덟 마리가 걸어요.",
  "One rabbit runs.": "토끼 한 마리가 달려요.",
  "I see a big dog.": "큰 개 한 마리가 보여요.",
  "The cat is cute.": "그 고양이는 귀여워요.",
  "A bird can fly.": "새는 날 수 있어요.",
  "Look at the rabbit!": "토끼를 보세요!",
  "My fish can swim.": "내 물고기는 헤엄칠 수 있어요.",
  "That duck is small.": "저 오리는 작아요.",
  "Can a frog jump?": "개구리는 뛸 수 있나요?",
  "Here is a monkey.": "여기 원숭이가 있어요.",
  "The pig is pink.": "그 돼지는 분홍색이에요.",
  "This cow is big.": "이 소는 커요.",
  "I like apples.": "나는 사과를 좋아해요.",
  "This cake is good.": "이 케이크는 맛있어요.",
  "Eat some rice.": "밥을 좀 먹어요.",
  "Have a banana.": "바나나를 먹어요.",
  "My soup is hot.": "내 수프는 뜨거워요.",
  "The bread is fresh.": "그 빵은 신선해요.",
  "Do you want pizza?": "피자 먹고 싶어요?",
  "She likes milk.": "그 아이는 우유를 좋아해요.",
  "He eats an egg.": "그 아이는 달걀을 먹어요.",
  "We have some fish.": "우리는 물고기가 몇 마리 있어요.",
  "I have a red pen.": "나는 빨간 펜이 있어요.",
  "My pencil is long.": "내 연필은 길어요.",
  "This is my ruler.": "이것은 내 자예요.",
  "That book is mine.": "저 책은 내 것이에요.",
  "Here is your bag.": "여기 네 가방이 있어요.",
  "I need some paper.": "나는 종이가 좀 필요해요.",
  "The eraser is pink.": "그 지우개는 분홍색이에요.",
  "Put the pen here.": "펜을 여기에 놓으세요.",
  "Open your notebook.": "공책을 펴세요.",
  "Use this blue pencil.": "이 파란 연필을 쓰세요.",
  "Hi, there!": "안녕!",
  "How are you?": "잘 지내니?",
  "I'm fine, thanks.": "잘 지내요, 고마워요.",
  "Good to see you.": "만나서 반가워요.",
  "Goodbye, Tom.": "잘 가, 톰.",
  "See you tomorrow.": "내일 봐요.",
  "I'm good, thank you.": "잘 지내요, 고마워요.",
  "Have fun today.": "오늘 즐겁게 보내요.",
  "So long, my friend.": "잘 가, 친구야.",
  "Hello, everyone.": "여러분, 안녕하세요.",
  "I am here.": "나는 여기 있어요.",
  "I am a visitor.": "나는 손님이에요.",
  "I am on a boat.": "나는 배를 타고 있어요.",
  "I am in a tent.": "나는 텐트 안에 있어요.",
  "I am on the bus.": "나는 버스를 타고 있어요.",
  "I am lost.": "나는 길을 잃었어요.",
  "I am tired.": "나는 피곤해요.",
  "I am on the plane.": "나는 비행기를 타고 있어요.",
  "I am away.": "나는 멀리 떠나 있어요.",
  "I am back home.": "나는 집에 돌아왔어요.",
  "It is a book.": "그것은 책이에요.",
  "It is my bag.": "그것은 내 가방이에요.",
  "It is a pencil.": "그것은 연필이에요.",
  "It is your desk.": "그것은 네 책상이에요.",
  "It is a chair.": "그것은 의자예요.",
  "It is my cup.": "그것은 내 컵이에요.",
  "It is a clock.": "그것은 시계예요.",
  "It is your bike.": "그것은 네 자전거예요.",
  "It is a ball.": "그것은 공이에요.",
  "It is my lunch.": "그것은 내 점심이에요.",
  "Is it sunny?": "날씨가 맑나요?",
  "Is it rainy?": "비가 오나요?",
  "Is it cloudy?": "날씨가 흐린가요?",
  "Is it windy?": "바람이 부나요?",
  "Is it hot?": "날씨가 더운가요?",
  "Is it cold?": "날씨가 추운가요?",
  "How is the weather?": "날씨가 어때요?",
  "Is it warm?": "날씨가 따뜻한가요?",
  "Is it cool?": "날씨가 시원한가요?",
  "Is it snowing?": "눈이 오나요?",
  "clock": "시계",
  "class": "수업",
  "clean": "깨끗한",
  "close": "닫다",
  "flower": "꽃",
  "floor": "바닥",
  "scared": "무서워하는",
  "shy": "부끄러워하는",
  "smile": "웃다",
  "start": "시작하다",
  "stay": "머무르다",
  "stand": "서다",
  "speak": "말하다",
  "spell": "철자를 말하다",
  "skip": "깡충깡충 뛰다",
  "hand": "손",
  "sand": "모래",
  "find": "찾다",
  "kind": "친절한",
  "paint": "칠하다",
  "plant": "식물",
  "point": "가리키다",
  "print": "인쇄하다",
  "bike": "자전거",
  "ride": "타다",
  "plane": "비행기",
  "drive": "운전하다",
  "take": "가져가다",
  "home": "집",
  "come": "오다",
  "time": "시간",
  "day": "날",
  "play": "놀다",
  "say": "말하다",
  "way": "길",
  "today": "오늘",
  "wait": "기다리다",
  "rain": "비",
  "train": "기차",
  "mail": "우편",
  "I run on Monday.": "나는 월요일에 달려요.",
  "We sing on Tuesday.": "우리는 화요일에 노래해요.",
  "I read on Wednesday.": "나는 수요일에 책을 읽어요.",
  "We swim on Thursday.": "우리는 목요일에 수영해요.",
  "I play on Friday.": "나는 금요일에 놀아요.",
  "We walk on Saturday.": "우리는 토요일에 걸어요.",
  "I rest on Sunday.": "나는 일요일에 쉬어요.",
  "Monday is a good day.": "월요일은 좋은 날이에요.",
  "Tuesday is my day.": "화요일은 나의 날이에요.",
  "Wednesday is sunny.": "수요일은 날씨가 맑아요.",
  "I play in January.": "나는 1월에 놀아요.",
  "We run in February.": "우리는 2월에 달려요.",
  "I sing in March.": "나는 3월에 노래해요.",
  "We walk in April.": "우리는 4월에 걸어요.",
  "I swim in May.": "나는 5월에 수영해요.",
  "We play in June.": "우리는 6월에 놀아요.",
  "I read in July.": "나는 7월에 책을 읽어요.",
  "We sing in August.": "우리는 8월에 노래해요.",
  "I run in September.": "나는 9월에 달려요.",
  "We walk in October.": "우리는 10월에 걸어요.",
  "mother": "엄마",
  "father": "아빠",
  "sister": "여자 형제",
  "family": "가족",
  "baby": "아기",
  "son": "아들",
  "parent": "부모",
  "grand": "웅장한",
  "eye": "눈",
  "nose": "코",
  "mouth": "입",
  "ear": "귀",
  "head": "머리",
  "face": "얼굴",
  "arm": "팔",
  "foot": "발",
  "shirt": "셔츠",
  "pants": "바지",
  "skirt": "치마",
  "dress": "원피스",
  "socks": "양말",
  "shoes": "신발",
  "coat": "외투",
  "jacket": "재킷",
  "jeans": "청바지",
  "shorts": "반바지",
  "This is my mom.": "이분은 우리 엄마예요.",
  "This is my dad.": "이분은 우리 아빠예요.",
  "This is my sister.": "이 아이는 내 여자 형제예요.",
  "This is my brother.": "이 아이는 내 남자 형제예요.",
  "This is my family.": "이 사람들은 우리 가족이에요.",
  "This is my grandma.": "이분은 우리 할머니예요.",
  "This is my grandpa.": "이분은 우리 할아버지예요.",
  "This is my aunt.": "이분은 우리 이모나 고모예요.",
  "This is my uncle.": "이분은 우리 삼촌이에요.",
  "This is my cousin.": "이 아이는 내 사촌이에요.",
  "I like baseball.": "나는 야구를 좋아해요.",
  "I like basketball.": "나는 농구를 좋아해요.",
  "I like swimming.": "나는 수영을 좋아해요.",
  "I like skating.": "나는 스케이트 타기를 좋아해요.",
  "I like skiing.": "나는 스키 타기를 좋아해요.",
  "I like running.": "나는 달리기를 좋아해요.",
  "I like jumping.": "나는 뛰기를 좋아해요.",
  "I like badminton.": "나는 배드민턴을 좋아해요.",
  "I like volleyball.": "나는 배구를 좋아해요.",
  "I like bowling.": "나는 볼링을 좋아해요.",
  "I have a ball.": "나는 공이 있어요.",
  "I have a doll.": "나는 인형이 있어요.",
  "I have a kite.": "나는 연이 있어요.",
  "I have a robot.": "나는 로봇이 있어요.",
  "I have a car.": "나는 자동차가 있어요.",
  "I have a plane.": "나는 비행기가 있어요.",
  "I have a train.": "나는 기차가 있어요.",
  "I have a boat.": "나는 배가 있어요.",
  "I have a bike.": "나는 자전거가 있어요.",
  "I have a yo-yo.": "나는 요요가 있어요.",
  "Come here, please.": "여기로 와 주세요.",
  "Sit here, please.": "여기에 앉아 주세요.",
  "Help me, please.": "나를 도와주세요.",
  "Wait for me, please.": "나를 기다려 주세요.",
  "Play with me, please.": "나와 같이 놀아 주세요.",
  "Look at me, please.": "나를 봐 주세요.",
  "Listen to me, please.": "내 말을 들어 주세요.",
  "Call me, please.": "나를 불러 주세요.",
  "Open it, please.": "그것을 열어 주세요.",
  "Close it, please.": "그것을 닫아 주세요.",
  "I like music.": "나는 음악을 좋아해요.",
  "I can sing.": "나는 노래할 수 있어요.",
  "We play soccer.": "우리는 축구를 해요.",
  "She can dance.": "그 아이는 춤출 수 있어요.",
  "He likes books.": "그 아이는 책을 좋아해요.",
  "I draw a cat.": "나는 고양이를 그려요.",
  "Let's ride a bike.": "자전거를 타요.",
  "Can you swim?": "수영할 수 있나요?",
  "They play games.": "그들은 게임을 해요.",
  "I read every day.": "나는 매일 책을 읽어요.",
  "blow": "불다",
  "blank": "빈",
  "blind": "눈이 먼",
  "clap": "박수치다",
  "climb": "오르다",
  "clown": "광대",
  "clip": "집게",
  "click": "누르다",
  "flute": "플루트",
  "flame": "불꽃",
  "snake": "뱀",
  "spider": "거미",
  "skunk": "스컹크",
  "snail": "달팽이",
  "swan": "백조",
  "shark": "상어",
  "skate": "스케이트를 타다",
  "stork": "황새",
  "slug": "민달팽이",
  "land": "땅",
  "friend": "친구",
  "band": "악단",
  "tent": "텐트",
  "want": "원하다",
  "went": "갔다",
  "front": "앞",
  "count": "세다",
  "like": "좋아하다",
  "make": "만들다",
  "cute": "귀여운",
  "rose": "장미",
  "nice": "좋은",
  "I play on Monday.": "나는 월요일에 놀아요.",
  "Tuesday is a fun day.": "화요일은 즐거운 날이에요.",
  "We read on Wednesday.": "우리는 수요일에 책을 읽어요.",
  "Thursday is my day.": "목요일은 나의 날이에요.",
  "It is Friday today.": "오늘은 금요일이에요.",
  "Come on Saturday.": "토요일에 오세요.",
  "See you on Sunday!": "일요일에 만나요!",
  "On Tuesday, we sing.": "우리는 화요일에 노래해요.",
  "This Wednesday is fun.": "이번 수요일은 즐거워요.",
  "Sunday is a sunny day.": "일요일은 날씨가 맑은 날이에요.",
  "January is cold.": "1월은 추워요.",
  "I smile in February.": "나는 2월에 웃어요.",
  "We are happy in April.": "우리는 4월에 행복해요.",
  "May is warm and nice.": "5월은 따뜻하고 좋아요.",
  "I feel good in June.": "나는 6월에 기분이 좋아요.",
  "July is a fun month.": "7월은 즐거운 달이에요.",
  "We are glad in August.": "우리는 8월에 기뻐요.",
  "September feels nice.": "9월은 기분 좋은 달이에요.",
  "I am happy in October.": "나는 10월에 행복해요.",
  "I smile in December.": "나는 12월에 웃어요.",
  "I love my mom.": "나는 엄마를 사랑해요.",
  "Dad can help me.": "아빠는 나를 도와줄 수 있어요.",
  "My mother is kind.": "우리 엄마는 친절해요.",
  "Father is at home.": "아빠는 집에 있어요.",
  "She is my sister.": "그 아이는 내 여자 형제예요.",
  "He is my brother.": "그 아이는 내 남자 형제예요.",
  "Grandma can cook.": "할머니는 요리할 수 있어요.",
  "Grandpa likes music.": "할아버지는 음악을 좋아해요.",
  "We are a family.": "우리는 한 가족이에요.",
  "Meet my parents.": "우리 부모님을 만나 보세요.",
  "Touch your head.": "머리를 만져 보세요.",
  "Show me your hand.": "손을 보여 주세요.",
  "Raise your arm.": "팔을 들어 보세요.",
  "Move your leg.": "다리를 움직여 보세요.",
  "My foot is small.": "내 발은 작아요.",
  "Wash your face.": "얼굴을 씻으세요.",
  "Close your eyes.": "눈을 감으세요.",
  "Open your mouth.": "입을 벌리세요.",
  "This is my nose.": "이것은 내 코예요.",
  "Her hair is long.": "그 아이의 머리카락은 길어요.",
  "I wear a blue cap.": "나는 파란 모자를 써요.",
  "Put on your coat.": "외투를 입으세요.",
  "Her dress is pink.": "그 아이의 원피스는 분홍색이에요.",
  "His shirt is green.": "그 아이의 셔츠는 초록색이에요.",
  "These socks are new.": "이 양말은 새것이에요.",
  "My pants are black.": "내 바지는 검은색이에요.",
  "That skirt is pretty.": "저 치마는 예뻐요.",
  "Take off your shoes.": "신발을 벗으세요.",
  "This hat is yellow.": "이 모자는 노란색이에요.",
  "Your jacket is nice.": "네 재킷은 멋져요.",
  "This is rain.": "이것은 비예요.",
  "This is snow.": "이것은 눈이에요.",
  "This is a cloud.": "이것은 구름이에요.",
  "This is the sun.": "이것은 해예요.",
  "This is a rainbow.": "이것은 무지개예요.",
  "This is a rainy day.": "비가 오는 날이에요.",
  "This is a sunny day.": "날씨가 맑은 날이에요.",
  "This is a cold day.": "오늘은 추운 날이에요.",
  "This is a hot day.": "오늘은 더운 날이에요.",
  "This is a warm day.": "오늘은 따뜻한 날이에요.",
  "I like my eyes.": "나는 내 눈이 좋아요.",
  "I like my nose.": "나는 내 코가 좋아요.",
  "I like my ears.": "나는 내 귀가 좋아요.",
  "I like my hair.": "나는 내 머리카락이 좋아요.",
  "I like my hands.": "나는 내 손이 좋아요.",
  "I like my feet.": "나는 내 발이 좋아요.",
  "I like my arms.": "나는 내 팔이 좋아요.",
  "I like my legs.": "나는 내 다리가 좋아요.",
  "I like my face.": "나는 내 얼굴이 좋아요.",
  "I like my smile.": "나는 내 웃는 모습이 좋아요.",
  "I have a pen.": "나는 펜이 있어요.",
  "I have a pencil.": "나는 연필이 있어요.",
  "I have a book.": "나는 책이 있어요.",
  "I have a ruler.": "나는 자가 있어요.",
  "I have an eraser.": "나는 지우개가 있어요.",
  "I have a bag.": "나는 가방이 있어요.",
  "I have a notebook.": "나는 공책이 있어요.",
  "I have a crayon.": "나는 크레용이 있어요.",
  "I have a desk.": "나는 책상이 있어요.",
  "I have a chair.": "나는 의자가 있어요.",
  "Wear your coat.": "외투를 입으세요.",
  "Put on your hat.": "모자를 쓰세요.",
  "Take your umbrella.": "우산을 챙기세요.",
  "Drink some water.": "물을 좀 마시세요.",
  "Please wear a cap.": "모자를 써 주세요.",
  "Let's go outside.": "밖으로 나가요.",
  "Come inside, please.": "안으로 들어오세요.",
  "Please close the door.": "문을 닫아 주세요.",
  "Look at the snow.": "눈을 보세요.",
  "Stay in the shade.": "그늘에 있으세요.",
  "I wear a blue shirt.": "나는 파란 셔츠를 입어요.",
  "This coat is warm.": "이 외투는 따뜻해요.",
  "My shoes are black.": "내 신발은 검은색이에요.",
  "She has a red dress.": "그 아이는 빨간 원피스가 있어요.",
  "He wears a green cap.": "그 아이는 초록색 모자를 써요.",
  "These socks are white.": "이 양말은 흰색이에요.",
  "I like this skirt.": "나는 이 치마가 좋아요.",
  "Are these your pants?": "이 바지는 네 것이니?",
  "That is my scarf.": "저것은 내 목도리예요.",
  "The boots are brown.": "그 장화는 갈색이에요.",
  "feet": "발",
  "heel": "발뒤꿈치",
  "teeth": "이",
  "cheek": "볼",
  "see": "보다",
  "need": "필요하다",
  "eat": "먹다",
  "hear": "듣다",
  "reach": "도착하다",
  "road": "길",
  "goal": "목표",
  "coach": "코치",
  "show": "보여 주다",
  "know": "알다",
  "row": "노를 젓다",
  "slow": "느린",
  "window": "창문",
  "ship": "배",
  "dish": "접시",
  "wash": "씻다",
  "brush": "솔",
  "chin": "턱",
  "chop": "썰다",
  "rich": "부자인",
  "much": "많은",
  "thin": "얇은",
  "thick": "두꺼운",
  "path": "길",
  "what": "무엇",
  "when": "언제",
  "which": "어느 것",
  "boys": "남자아이들",
  "girls": "여자아이들",
  "babies": "아기들",
  "cousins": "사촌들",
  "parents": "부모님",
  "sisters": "여자 형제들",
  "aunts": "이모나 고모들",
  "uncles": "삼촌들",
  "mothers": "엄마들",
  "fathers": "아빠들",
  "house": "집",
  "room": "방",
  "kitchen": "부엌",
  "door": "문",
  "wall": "벽",
  "roof": "지붕",
  "yard": "마당",
  "garden": "정원",
  "sunny": "맑은",
  "rainy": "비 오는",
  "cloudy": "흐린",
  "windy": "바람 부는",
  "snowy": "눈 오는",
  "cold": "추운",
  "warm": "따뜻한",
  "cool": "시원한",
  "foggy": "안개 낀",
  "You can jump high.": "너는 높이 뛸 수 있어요.",
  "We can play soccer.": "우리는 축구를 할 수 있어요.",
  "He can ride a bike.": "그 아이는 자전거를 탈 수 있어요.",
  "She can sing well.": "그 아이는 노래를 잘할 수 있어요.",
  "They can swim together.": "그들은 함께 수영할 수 있어요.",
  "My friend can dance.": "내 친구는 춤을 출 수 있어요.",
  "A boy can draw a cat.": "한 남자아이가 고양이를 그릴 수 있어요.",
  "A girl can read aloud.": "한 여자아이가 소리 내어 읽을 수 있어요.",
  "Tom can throw a ball.": "톰은 공을 던질 수 있어요.",
  "Jane can make a kite.": "제인은 연을 만들 수 있어요.",
  "What is your hobby?": "네 취미는 무엇이니?",
  "What do you like to do?": "너는 무엇을 하기를 좋아하니?",
  "What game do you play?": "너는 무슨 게임을 하니?",
  "What sport do you like?": "너는 무슨 운동을 좋아하니?",
  "What do you draw?": "너는 무엇을 그리니?",
  "What book do you read?": "너는 무슨 책을 읽니?",
  "What song do you sing?": "너는 무슨 노래를 부르니?",
  "What can you make?": "너는 무엇을 만들 수 있니?",
  "What do they play?": "그들은 무엇을 하니?",
  "What does he like?": "그 아이는 무엇을 좋아하니?",
  "How many songs do you know?": "너는 노래를 몇 곡 알고 있니?",
  "How many drums do you see?": "북이 몇 개 보이니?",
  "How many pianos are there?": "피아노가 몇 대 있니?",
  "How many bells can you hear?": "종소리가 몇 개 들리니?",
  "How many notes can you read?": "음표를 몇 개 읽을 수 있니?",
  "How many flutes do we have?": "우리에게 플루트가 몇 개 있니?",
  "How many guitars are there?": "기타가 몇 개 있니?",
  "How many singers do you see?": "노래하는 사람이 몇 명 보이니?",
  "How many bands do you like?": "너는 몇 개의 밴드를 좋아하니?",
  "How many dances do they know?": "그들은 춤을 몇 가지 알고 있니?",
  "It is warm in spring.": "봄에는 따뜻해요.",
  "Birds sing in spring.": "새들은 봄에 노래해요.",
  "Bears wake up in spring.": "곰들은 봄에 잠에서 깨어나요.",
  "I see bees in spring.": "나는 봄에 벌들을 봐요.",
  "Rabbits play in spring.": "토끼들은 봄에 놀아요.",
  "Ducks swim in summer.": "오리들은 여름에 헤엄쳐요.",
  "It is hot in summer.": "여름에는 더워요.",
  "Fish swim in summer.": "물고기들은 여름에 헤엄쳐요.",
  "Frogs jump in summer.": "개구리들은 여름에 뛰어요.",
  "Cats sleep in summer.": "고양이들은 여름에 잠을 자요.",
  "I like my room.": "나는 내 방이 좋아요.",
  "We like our home.": "우리는 우리 집을 좋아해요.",
  "She likes the kitchen.": "그 아이는 부엌을 좋아해요.",
  "He likes his bed.": "그 아이는 자기 침대를 좋아해요.",
  "They like the living room.": "그들은 거실을 좋아해요.",
  "Mom likes the garden.": "엄마는 정원을 좋아해요.",
  "Dad likes the big table.": "아빠는 큰 탁자를 좋아해요.",
  "My sister likes her chair.": "내 여자 형제는 자기 의자를 좋아해요.",
  "My brother likes the yard.": "내 남자 형제는 마당을 좋아해요.",
  "I don't like this door.": "나는 이 문이 마음에 들지 않아요.",
  "Birds fly in the sky.": "새들은 하늘을 날아요.",
  "Fish swim in the river.": "물고기들은 강에서 헤엄쳐요.",
  "Bees visit flowers.": "벌들은 꽃을 찾아가요.",
  "The sun shines brightly.": "해가 밝게 빛나요.",
  "Rain falls from the sky.": "하늘에서 비가 내려요.",
  "Trees grow in the forest.": "나무들은 숲에서 자라요.",
  "A frog jumps by the pond.": "개구리 한 마리가 연못가에서 뛰어요.",
  "Clouds move in the sky.": "구름이 하늘에서 움직여요.",
  "The wind moves the leaves.": "바람이 나뭇잎을 움직여요.",
  "Ants walk on the ground.": "개미들이 땅 위를 걸어요.",
  "I have some rice.": "나는 밥이 좀 있어요.",
  "We have fresh milk.": "우리는 신선한 우유가 있어요.",
  "Do you have bread?": "빵이 있나요?",
  "She has an apple.": "그 아이는 사과 한 개가 있어요.",
  "He has some soup.": "그 아이는 수프가 좀 있어요.",
  "I don't have juice.": "나는 주스가 없어요.",
  "We don't have eggs.": "우리는 달걀이 없어요.",
  "Does she have cake?": "그 아이는 케이크가 있나요?",
  "He doesn't have fish.": "그 아이는 생선이 없어요.",
  "They have bananas.": "그들은 바나나가 있어요.",
  "Go straight ahead.": "앞으로 곧장 가세요.",
  "Turn left here.": "여기에서 왼쪽으로 도세요.",
  "Where is the zoo?": "동물원이 어디에 있나요?",
  "The park is big.": "그 공원은 커요.",
  "Is it near the bus stop?": "버스 정류장 근처에 있나요?",
  "It is next to the bank.": "은행 바로 옆에 있어요.",
  "I see the hospital.": "병원이 보여요.",
  "Walk to the library.": "도서관까지 걸어가세요.",
  "Turn right at the bakery.": "빵집에서 오른쪽으로 도세요.",
  "The store is open.": "가게가 열려 있어요.",
  "rainbow": "무지개",
  "glow": "빛나다",
  "snow": "눈",
  "low": "낮은",
  "grow": "자라다",
  "boat": "배",
  "goat": "염소",
  "soap": "비누",
  "toast": "토스트",
  "shoe": "신발",
  "short": "짧은",
  "shine": "빛나다",
  "fresh": "신선한",
  "beach": "해변",
  "cheese": "치즈",
  "chick": "병아리",
  "child": "아이",
  "this": "이것",
  "that": "저것",
  "these": "이것들",
  "those": "저것들",
  "they": "그들",
  "them": "그들을",
  "then": "그때",
  "there": "거기에",
  "why": "왜",
  "who": "누구",
  "days": "날들",
  "clouds": "구름들",
  "winds": "바람들",
  "storms": "폭풍들",
  "skies": "하늘들",
  "drops": "방울들",
  "boxes": "상자들",
  "trees": "나무들",
  "flowers": "꽃들",
  "birds": "새들",
  "My house has a kitchen.": "우리 집에는 부엌이 있어요.",
  "The bedroom is upstairs.": "침실은 위층에 있어요.",
  "We eat in the dining room.": "우리는 식당에서 밥을 먹어요.",
  "Come into the living room.": "거실로 들어오세요.",
  "My bed is in this room.": "내 침대는 이 방에 있어요.",
  "The bathroom is over there.": "화장실은 저쪽에 있어요.",
  "Our kitchen is very clean.": "우리 부엌은 아주 깨끗해요.",
  "There is a table inside.": "안에 탁자가 있어요.",
  "Is your room next to mine?": "네 방은 내 방 옆에 있니?",
  "Dad is in the living room.": "아빠는 거실에 계세요.",
  "It is sunny today.": "오늘은 날씨가 맑아요.",
  "The sky is cloudy.": "하늘에 구름이 많아요.",
  "We have a rainy day.": "오늘은 비가 오는 날이에요.",
  "It is cold outside.": "밖은 추워요.",
  "Today is warm and sunny.": "오늘은 따뜻하고 맑아요.",
  "The wind is very strong.": "바람이 아주 세게 불어요.",
  "Look at the dark clouds.": "검은 구름을 보세요.",
  "Snow is falling outside.": "밖에 눈이 내리고 있어요.",
  "Is it hot today?": "오늘은 덥니?",
  "I like cool weather.": "나는 선선한 날씨를 좋아해요.",
  "I can ski in winter.": "나는 겨울에 스키를 탈 수 있어요.",
  "We can camp in summer.": "우리는 여름에 캠핑을 할 수 있어요.",
  "You can see spring flowers.": "봄꽃을 볼 수 있어요.",
  "He can fly a kite in fall.": "그는 가을에 연을 날릴 수 있어요.",
  "She can make a snowman.": "그녀는 눈사람을 만들 수 있어요.",
  "They can eat cold food.": "그들은 차가운 음식을 먹을 수 있어요.",
  "My family can go outside.": "우리 가족은 밖에 나갈 수 있어요.",
  "A bird can sit in a tree.": "새가 나무에 앉을 수 있어요.",
  "Bees can come in spring.": "봄에는 벌들이 찾아올 수 있어요.",
  "Leaves can fall in fall.": "가을에는 나뭇잎이 떨어질 수 있어요.",
  "What are you wearing?": "너는 무엇을 입고 있니?",
  "What color is your shirt?": "네 셔츠는 무슨 색이니?",
  "What do you wear outside?": "밖에 나갈 때 무엇을 입니?",
  "What does she wear?": "그녀는 무엇을 입니?",
  "What does he have on?": "그는 무엇을 입고 있니?",
  "What color are your pants?": "네 바지는 무슨 색이니?",
  "What is on your head?": "네 머리에는 무엇이 있니?",
  "What can I wear today?": "오늘 무엇을 입으면 될까?",
  "What is her dress like?": "그녀의 원피스는 어떻게 생겼니?",
  "What color is his cap?": "그의 모자는 무슨 색이니?",
  "How many brothers do you have?": "남자 형제가 몇 명 있니?",
  "How many sisters do you have?": "여자 형제가 몇 명 있니?",
  "How many babies are there?": "아기가 몇 명 있니?",
  "How many parents do you see?": "부모님이 몇 분 보이니?",
  "How many cousins are here?": "사촌이 여기 몇 명 있니?",
  "How many uncles do they have?": "그들에게 삼촌이 몇 명 있니?",
  "How many aunts can you see?": "이모나 고모가 몇 명 보이니?",
  "How many children are at home?": "집에 아이들이 몇 명 있니?",
  "How many families live here?": "여기에 몇 가족이 살고 있니?",
  "How many sons does she have?": "그녀에게 아들이 몇 명 있니?",
  "We ski in winter.": "우리는 겨울에 스키를 타요.",
  "I skate in winter.": "나는 겨울에 스케이트를 타요.",
  "They run in fall.": "그들은 가을에 달려요.",
  "He plays soccer in fall.": "그는 가을에 축구를 해요.",
  "She plays tennis in fall.": "그녀는 가을에 테니스를 쳐요.",
  "We play hockey in winter.": "우리는 겨울에 하키를 해요.",
  "I jump rope in fall.": "나는 가을에 줄넘기를 해요.",
  "They play games in winter.": "그들은 겨울에 게임을 해요.",
  "He rides a bike in fall.": "그는 가을에 자전거를 타요.",
  "She walks fast in winter.": "그녀는 겨울에 빨리 걸어요.",
  "I like this ball.": "나는 이 공을 좋아해요.",
  "You like that kite.": "너는 저 연을 좋아해요.",
  "She likes her doll.": "그녀는 자기 인형을 좋아해요.",
  "He likes toy cars.": "그는 장난감 자동차를 좋아해요.",
  "They like the blocks.": "그들은 블록을 좋아해요.",
  "We like the robot.": "우리는 그 로봇을 좋아해요.",
  "My friend likes the train.": "내 친구는 그 기차를 좋아해요.",
  "The boy likes his top.": "그 남자아이는 자기 팽이를 좋아해요.",
  "The girl likes the puzzle.": "그 여자아이는 퍼즐을 좋아해요.",
  "I don't like that drum.": "나는 저 북을 좋아하지 않아요.",
  "I play with my friend.": "나는 친구와 함께 놀아요.",
  "You help your friend.": "너는 친구를 도와줘요.",
  "We study together.": "우리는 함께 공부해요.",
  "She reads with a friend.": "그녀는 친구와 함께 책을 읽어요.",
  "He plays ball with me.": "그는 나와 함께 공놀이를 해요.",
  "They walk to school.": "그들은 걸어서 학교에 가요.",
  "My friend draws a picture.": "내 친구는 그림을 그려요.",
  "The boys play a game.": "남자아이들은 게임을 해요.",
  "Two girls sing together.": "두 여자아이가 함께 노래해요.",
  "Our friends eat lunch.": "우리 친구들은 점심을 먹어요.",
  "I have a fun hobby.": "나는 재미있는 취미가 있어요.",
  "We have two kites.": "우리는 연이 두 개 있어요.",
  "Do you have a bike?": "너는 자전거가 있니?",
  "She has a new ball.": "그녀는 새 공이 있어요.",
  "He has a toy plane.": "그는 장난감 비행기가 있어요.",
  "I don't have a puzzle.": "나는 퍼즐이 없어요.",
  "We don't have a game.": "우리는 게임이 없어요.",
  "Does she have a doll?": "그녀는 인형이 있니?",
  "He doesn't have a robot.": "그는 로봇이 없어요.",
  "They have comic books.": "그들은 만화책이 있어요.",
  "Listen to the music.": "음악을 들어 보세요.",
  "She can play the piano.": "그녀는 피아노를 칠 수 있어요.",
  "Sing a happy song.": "신나는 노래를 불러 보세요.",
  "I like this drum.": "나는 이 북을 좋아해요.",
  "He plays the violin well.": "그는 바이올린을 잘 켜요.",
  "Dance to the beat.": "박자에 맞춰 춤을 추세요.",
  "This flute is loud.": "이 플루트 소리는 커요.",
  "Join the school band.": "학교 악단에 들어가세요.",
  "We practice together.": "우리는 함께 연습해요.",
  "Hear the sweet sound.": "아름다운 소리를 들어 보세요.",
  "scarf": "목도리",
  "yarn": "털실",
  "cord": "끈",
  "dark": "어두운",
  "parka": "두꺼운 외투",
  "party": "파티",
  "worn": "낡은",
  "charm": "장식",
  "brother": "남자 형제",
  "girl": "여자아이",
  "nurse": "간호사",
  "helper": "도우미",
  "person": "사람",
  "older": "더 나이 많은",
  "teacher": "선생님",
  "doctor": "의사",
  "cook": "요리사",
  "farmer": "농부",
  "singer": "가수",
  "driver": "운전사",
  "pilot": "조종사",
  "artist": "화가",
  "police": "경찰",
  "school": "학교",
  "park": "공원",
  "library": "도서관",
  "hospital": "병원",
  "museum": "박물관",
  "market": "시장",
  "store": "가게",
  "zoo": "동물원",
  "farm": "농장",
  "soccer": "축구",
  "baseball": "야구",
  "basketball": "농구",
  "tennis": "테니스",
  "swimming": "수영",
  "running": "달리기",
  "skating": "스케이트 타기",
  "skiing": "스키 타기",
  "fishing": "낚시",
  "camping": "캠핑",
  "A dog is running.": "개 한 마리가 달리고 있어요.",
  "The cat is sleeping.": "고양이가 자고 있어요.",
  "My bird is singing.": "내 새가 노래하고 있어요.",
  "That rabbit is jumping.": "저 토끼가 뛰고 있어요.",
  "A duck is swimming.": "오리 한 마리가 헤엄치고 있어요.",
  "The horse is eating.": "말이 먹이를 먹고 있어요.",
  "Our cow is walking.": "우리 소가 걷고 있어요.",
  "This pig is drinking.": "이 돼지가 물을 마시고 있어요.",
  "One monkey is climbing.": "원숭이 한 마리가 올라가고 있어요.",
  "Your bear is sitting.": "네 곰이 앉아 있어요.",
  "Where is my book?": "내 책은 어디에 있니?",
  "Where is the chair?": "의자는 어디에 있니?",
  "Where is your bag?": "네 가방은 어디에 있니?",
  "Where is my cup?": "내 컵은 어디에 있니?",
  "Where is the table?": "탁자는 어디에 있니?",
  "Where is Mom?": "엄마는 어디에 계시니?",
  "Where is my bed?": "내 침대는 어디에 있니?",
  "Where is the clock?": "시계는 어디에 있니?",
  "Where is Dad?": "아빠는 어디에 계시니?",
  "Where is the kitchen?": "부엌은 어디에 있니?",
  "When is spring?": "봄은 언제니?",
  "When is summer?": "여름은 언제니?",
  "When is winter?": "겨울은 언제니?",
  "When is fall?": "가을은 언제니?",
  "When does it rain?": "비는 언제 오니?",
  "When does snow fall?": "눈은 언제 내리니?",
  "When do flowers grow?": "꽃은 언제 자라니?",
  "When do birds sing?": "새들은 언제 노래하니?",
  "When does the sun rise?": "해는 언제 뜨니?",
  "When do leaves fall?": "나뭇잎은 언제 떨어지니?",
  "It's seven o'clock.": "일곱 시예요.",
  "It's twelve o'clock.": "열두 시예요.",
  "Lunch is at one.": "점심은 한 시에 먹어요.",
  "Dinner is at six.": "저녁은 여섯 시에 먹어요.",
  "Breakfast is at eight.": "아침은 여덟 시에 먹어요.",
  "We eat at five.": "우리는 다섯 시에 먹어요.",
  "I eat lunch at noon.": "나는 낮 열두 시에 점심을 먹어요.",
  "It's nine thirty.": "아홉 시 삼십 분이에요.",
  "Snack time is at three.": "간식 시간은 세 시예요.",
  "We have lunch at eleven.": "우리는 열한 시에 점심을 먹어요.",
  "Go straight one block.": "한 블록 곧장 가세요.",
  "The park is over there.": "공원은 저쪽에 있어요.",
  "It is behind the bank.": "그곳은 은행 뒤에 있어요.",
  "A post office is near.": "우체국이 가까이에 있어요.",
  "Is it next to the zoo?": "그곳은 동물원 옆에 있나요?",
  "Turn left at the mart.": "마트에서 왼쪽으로 도세요.",
  "My school is right here.": "우리 학교는 바로 여기에 있어요.",
  "The bookstore is ahead.": "서점은 앞쪽에 있어요.",
  "Walk two blocks down.": "두 블록 걸어가세요.",
  "The museum is far away.": "박물관은 멀리 있어요.",
  "I put on a red shirt.": "나는 빨간 셔츠를 입어요.",
  "She draws with blue ink.": "그녀는 파란 잉크로 그림을 그려요.",
  "Brush with a pink cup.": "분홍색 컵을 쓰며 이를 닦아요.",
  "He rides a yellow bike.": "그는 노란 자전거를 타요.",
  "We read the green book.": "우리는 초록색 책을 읽어요.",
  "Wash your white socks.": "네 흰 양말을 빨아요.",
  "Find my orange cap today.": "오늘 내 주황색 모자를 찾아 주세요.",
  "Eat a sweet purple grape.": "달콤한 보라색 포도를 먹어요.",
  "They take brown shoes.": "그들은 갈색 신발을 가져가요.",
  "Paint the gray fence now.": "지금 울타리를 회색으로 칠하세요.",
  "I pack my red bag.": "나는 빨간 가방에 짐을 챙겨요.",
  "We go to the beach.": "우리는 바닷가에 가요.",
  "Take a bus together.": "함께 버스를 타요.",
  "Where is your ticket?": "네 표는 어디에 있니?",
  "He rides a blue train.": "그는 파란 기차를 타요.",
  "Let's visit my grandma.": "우리 할머니를 만나러 가요.",
  "They stay at a hotel.": "그들은 호텔에서 지내요.",
  "She wants to travel.": "그녀는 여행하고 싶어 해요.",
  "Walk along the street.": "길을 따라 걸어가세요.",
  "Look at the big plane.": "큰 비행기를 보세요.",
  "morning": "아침",
  "alarm": "알람",
  "fork": "포크",
  "chore": "집안일",
  "order": "주문하다",
  "card": "카드",
  "corn": "옥수수",
  "winter": "겨울",
  "summer": "여름",
  "thunder": "천둥",
  "shower": "샤워",
  "turn": "돌다",
  "shiver": "떨다",
  "burn": "타다",
  "river": "강",
  "hurt": "아프다",
  "knee": "무릎",
  "wrist": "손목",
  "knuckle": "손가락 마디",
  "knelt": "무릎 꿇었다",
  "wrinkle": "주름",
  "walk": "걷다",
  "knew": "알았다",
  "knife": "칼",
  "wrote": "썼다",
  "could": "할 수 있었다",
  "would": "할 것이다",
  "should": "해야 한다",
  "folk": "사람들",
  "yolk": "노른자",
  "tomb": "무덤",
  "climber": "오르는 사람",
  "climbing": "오르기",
  "thumbs": "엄지손가락들",
  "walked": "걸었다",
  "My dad is a cook.": "우리 아빠는 요리사예요.",
  "She wants to be a doctor.": "그녀는 의사가 되고 싶어 해요.",
  "The farmer grows food.": "농부는 먹을 것을 길러요.",
  "A teacher helps students.": "선생님은 학생들을 도와줘요.",
  "He works as a police officer.": "그는 경찰관으로 일해요.",
  "The nurse helps sick people.": "간호사는 아픈 사람들을 도와줘요.",
  "Her mom is a bus driver.": "그녀의 엄마는 버스 운전사예요.",
  "I want to be a singer.": "나는 가수가 되고 싶어요.",
  "That man is a firefighter.": "저 남자는 소방관이에요.",
  "The baker makes good bread.": "제빵사는 맛있는 빵을 만들어요.",
  "I am at the library.": "나는 도서관에 있어요.",
  "She goes to the park.": "그녀는 공원에 가요.",
  "Meet me at the school.": "학교에서 만나요.",
  "The bank is over there.": "은행은 저쪽에 있어요.",
  "We play at the playground.": "우리는 놀이터에서 놀아요.",
  "He is in the classroom.": "그는 교실에 있어요.",
  "Is the store near here?": "가게가 여기 가까이에 있나요?",
  "Go straight to the hospital.": "병원까지 곧장 가세요.",
  "They walk to the station.": "그들은 역까지 걸어가요.",
  "The restaurant is nearby.": "식당은 가까이에 있어요.",
  "I like playing soccer.": "나는 축구하는 것을 좋아해요.",
  "She can play baseball.": "그녀는 야구를 할 수 있어요.",
  "We play basketball today.": "우리는 오늘 농구를 해요.",
  "He enjoys riding a bike.": "그는 자전거 타는 것을 좋아해요.",
  "Do you like swimming?": "너는 수영하는 것을 좋아하니?",
  "My hobby is drawing.": "내 취미는 그림 그리기예요.",
  "They play badminton well.": "그들은 배드민턴을 잘 쳐요.",
  "Let's go hiking together.": "함께 등산하러 가요.",
  "Reading books is my hobby.": "내 취미는 책 읽기예요.",
  "Can you play table tennis?": "너는 탁구를 칠 수 있니?",
  "She is skiing.": "그녀는 스키를 타고 있어요.",
  "He is kicking a ball.": "그는 공을 차고 있어요.",
  "We are playing soccer.": "우리는 축구를 하고 있어요.",
  "They are riding bikes.": "그들은 자전거를 타고 있어요.",
  "My friend is bowling.": "내 친구는 볼링을 하고 있어요.",
  "Tom is playing tennis.": "톰은 테니스를 치고 있어요.",
  "Jane is catching a ball.": "제인은 공을 잡고 있어요.",
  "You are throwing a ball.": "너는 공을 던지고 있어요.",
  "Sam is playing baseball.": "샘은 야구를 하고 있어요.",
  "Amy is dancing now.": "에이미는 지금 춤을 추고 있어요.",
  "Where is my ball?": "내 공은 어디에 있니?",
  "Where is the robot?": "로봇은 어디에 있니?",
  "Where is your doll?": "네 인형은 어디에 있니?",
  "Where is my kite?": "내 연은 어디에 있니?",
  "Where is the toy car?": "장난감 자동차는 어디에 있니?",
  "Where is your bike?": "네 자전거는 어디에 있니?",
  "Where is the box?": "상자는 어디에 있니?",
  "Where is my bear?": "내 곰 인형은 어디에 있니?",
  "Where is the train?": "기차는 어디에 있니?",
  "Where is your plane?": "네 비행기는 어디에 있니?",
  "When is your birthday?": "네 생일은 언제니?",
  "When is the party?": "파티는 언제니?",
  "When do we meet?": "우리는 언제 만나니?",
  "When can you play?": "너는 언제 놀 수 있니?",
  "When can she come?": "그녀는 언제 올 수 있니?",
  "When can he visit?": "그는 언제 찾아올 수 있니?",
  "When is our game?": "우리 경기는 언제니?",
  "When is your class?": "네 수업은 언제니?",
  "When do you go home?": "너는 언제 집에 가니?",
  "When can we talk?": "우리는 언제 이야기할 수 있니?",
  "It's two o'clock.": "두 시예요.",
  "It's four o'clock.": "네 시예요.",
  "It's five thirty.": "다섯 시 삼십 분이에요.",
  "Soccer starts at three.": "축구는 세 시에 시작해요.",
  "I swim at four thirty.": "나는 네 시 삼십 분에 수영해요.",
  "We play at two.": "우리는 두 시에 놀아요.",
  "I read at eight.": "나는 여덟 시에 책을 읽어요.",
  "Dance class is at five.": "춤 수업은 다섯 시에 있어요.",
  "I skate at nine.": "나는 아홉 시에 스케이트를 타요.",
  "Music starts at ten.": "음악 수업은 열 시에 시작해요.",
  "The drum is on the stage.": "북은 무대 위에 있어요.",
  "Put the flute in the box.": "플루트를 상자 안에 넣으세요.",
  "The piano is by the door.": "피아노는 문 옆에 있어요.",
  "Where is my violin?": "내 바이올린은 어디에 있니?",
  "The guitar is under the bed.": "기타는 침대 아래에 있어요.",
  "Look inside the music room.": "음악실 안을 보세요.",
  "Your bell is near the wall.": "네 종은 벽 가까이에 있어요.",
  "A trumpet is on that chair.": "트럼펫이 저 의자 위에 있어요.",
  "Her recorder is in the bag.": "그녀의 리코더는 가방 안에 있어요.",
  "Find the horn near the desk.": "책상 가까이에 있는 호른을 찾으세요.",
  "Where can I see the bear?": "곰은 어디에서 볼 수 있나요?",
  "Go down one block.": "한 블록 쭉 가세요.",
  "Turn right at the big tree.": "큰 나무에서 오른쪽으로 도세요.",
  "Find the cat hospital.": "고양이 병원을 찾으세요.",
  "Walk past the brown dog.": "갈색 개를 지나서 걸어가세요.",
  "How can we reach the zoo?": "동물원에 어떻게 갈 수 있나요?",
  "Turn left by the horse.": "말 옆에서 왼쪽으로 도세요.",
  "It is next to the pig farm.": "그곳은 돼지 농장 옆에 있어요.",
  "Look behind the cow shed.": "외양간 뒤를 보세요.",
  "The rabbit shop is ahead.": "토끼 가게는 앞쪽에 있어요.",
  "Wake up in my room.": "내 방에서 잠을 깨요.",
  "Make the bed every morning.": "매일 아침 침대를 정리해요.",
  "Cook breakfast at home.": "집에서 아침밥을 만들어요.",
  "Help dad clean the floor.": "아빠가 바닥을 청소하는 것을 도와드려요.",
  "Do homework by the desk.": "책상 옆에서 숙제를 해요.",
  "Wash dishes in the sink.": "싱크대에서 설거지를 해요.",
  "Feed my small pet inside.": "안에서 내 작은 반려동물에게 먹이를 줘요.",
  "Watch TV on the sofa.": "소파에서 텔레비전을 봐요.",
  "Take a rest after lunch.": "점심을 먹고 쉬어요.",
  "Open all the windows.": "창문을 모두 여세요.",
  "Look at that tall tree.": "저 키 큰 나무를 보세요.",
  "Leaves fall in autumn.": "가을에는 나뭇잎이 떨어져요.",
  "Rain falls from clouds.": "구름에서 비가 내려요.",
  "The deep river flows.": "깊은 강물이 흘러요.",
  "Smell the sweet flower.": "향기로운 꽃의 냄새를 맡아 보세요.",
  "Birds sing on the hill.": "새들이 언덕에서 노래해요.",
  "We walk in the forest.": "우리는 숲속을 걸어요.",
  "Wind blows softly here.": "여기에는 바람이 부드럽게 불어요.",
  "Watch the night stars.": "밤하늘의 별을 보세요.",
  "A frog lives in water.": "개구리는 물에서 살아요.",
  "moon": "달",
  "food": "음식",
  "pool": "수영장",
  "soon": "곧",
  "tooth": "이",
  "spoon": "숟가락",
  "out": "밖으로",
  "round": "둥근",
  "sound": "소리",
  "cloud": "구름",
  "ground": "땅",
  "found": "찾았다",
  "loud": "시끄러운",
  "oil": "기름",
  "coin": "동전",
  "join": "함께하다",
  "voice": "목소리",
  "noise": "소음",
  "boil": "끓이다",
  "soil": "흙",
  "toilet": "화장실",
  "choice": "선택",
  "butter": "버터",
  "little": "작은",
  "grass": "풀",
  "cherry": "체리",
  "noodle": "국수",
  "pickle": "피클",
  "waffle": "와플",
  "popsicle": "아이스바",
  "pineapple": "파인애플",
  "vegetable": "채소",
  "bottle": "병",
  "table": "탁자",
  "kettle": "주전자",
  "angry": "화난",
  "afraid": "무서워하는",
  "glad": "기쁜",
  "sorry": "미안한",
  "worried": "걱정하는",
  "excited": "신이 난",
  "surprised": "놀란",
  "proud": "자랑스러운",
  "forest": "숲",
  "mountain": "산",
  "ocean": "바다",
  "island": "섬",
  "sky": "하늘",
  "I painted a blue box.": "나는 상자를 파란색으로 칠했어요.",
  "She mixed red and white.": "그녀는 빨간색과 흰색을 섞었어요.",
  "We colored the green tree.": "우리는 나무를 초록색으로 칠했어요.",
  "He liked the yellow cap.": "그는 노란 모자를 좋아했어요.",
  "They picked purple flowers.": "그들은 보라색 꽃을 땄어요.",
  "My sister changed the orange dress.": "내 여자 형제는 주황색 원피스를 바꿨어요.",
  "The painter used bright pink.": "화가는 밝은 분홍색을 사용했어요.",
  "Mom matched brown shoes.": "엄마는 갈색 신발을 잘 어울리게 맞췄어요.",
  "Everyone loved the gray cat.": "모두가 회색 고양이를 좋아했어요.",
  "You rolled a black ball.": "너는 검은 공을 굴렸어요.",
  "We can see the blue sea today.": "우리는 오늘 푸른 바다를 볼 수 있어요.",
  "Did you buy a ticket by the gate?": "너는 입구 옆에서 표를 샀니?",
  "Two girls want to visit the town, too.": "두 여자아이도 그 마을에 가 보고 싶어 해요.",
  "He ate eight sweet apples on the bus.": "그는 버스에서 달콤한 사과 여덟 개를 먹었어요.",
  "They will meet by the meat shop.": "그들은 고기 가게 옆에서 만날 거예요.",
  "She rode along the wide dirt road.": "그녀는 넓은 흙길을 따라 타고 갔어요.",
  "I hear no train sounds from here.": "여기서는 기차 소리가 들리지 않아요.",
  "Our family had a nice one-hour trip.": "우리 가족은 한 시간 동안 즐겁게 여행했어요.",
  "Can you write down the right address?": "올바른 주소를 적어 줄 수 있니?",
  "We took a new plane to a plain hill.": "우리는 평평한 언덕으로 가려고 새 비행기를 탔어요.",
  "Can I borrow your pencil, please?": "네 연필을 빌려도 될까요?",
  "Sure, you can use my notebook.": "물론이죠, 내 공책을 써도 돼요.",
  "May I wash my hands now?": "지금 손을 씻어도 될까요?",
  "Please open the classroom door.": "교실 문을 열어 주세요.",
  "Could you help me clean this desk?": "이 책상을 청소하는 것을 도와줄 수 있나요?",
  "Yes, you may watch television.": "네, 텔레비전을 봐도 돼요.",
  "Would you turn off the light?": "불을 꺼 주시겠어요?",
  "Of course, take a short rest.": "물론이죠, 잠깐 쉬세요.",
  "Can you feed the cute dog today?": "오늘 귀여운 개에게 먹이를 줄 수 있니?",
  "No, you cannot play outside now.": "아니요, 지금은 밖에서 놀 수 없어요.",
  "It is warmer today.": "오늘은 더 따뜻해요.",
  "Summer is hotter than spring.": "여름은 봄보다 더 더워요.",
  "Today is cooler than yesterday.": "오늘은 어제보다 더 선선해요.",
  "This winter is colder.": "이번 겨울은 더 추워요.",
  "The wind is stronger now.": "지금은 바람이 더 세요.",
  "Is it sunnier over here?": "이쪽이 더 맑은가요?",
  "Which day is cloudier?": "어느 날이 구름이 더 많나요?",
  "Today feels drier than usual.": "오늘은 평소보다 더 건조해요.",
  "The night is darker today.": "오늘 밤은 더 어두워요.",
  "This room is brighter now.": "이 방은 지금 더 밝아요.",
  "Let's read books in the library.": "도서관에서 책을 읽어요.",
  "Shall we walk to the classroom?": "교실까지 걸어갈까요?",
  "Why don't we do our homework?": "우리 숙제를 하는 게 어때요?",
  "How about asking the teacher?": "선생님께 여쭤보는 게 어때요?",
  "What about having lunch together?": "함께 점심을 먹는 게 어때요?",
  "Would you like to visit my school?": "우리 학교에 와 보고 싶나요?",
  "Let us clean the wide art room.": "넓은 미술실을 함께 청소해요.",
  "Can we play soccer in the gym?": "체육관에서 축구를 해도 될까요?",
  "Why not practice science today?": "오늘 과학 공부를 해 보는 게 어때요?",
  "Shall we study English now?": "우리 지금 영어 공부를 할까요?",
  "I planted flowers in spring.": "나는 봄에 꽃을 심었어요.",
  "We swam at the pool last summer.": "우리는 지난여름에 수영장에서 수영했어요.",
  "He picked apples this fall.": "그는 이번 가을에 사과를 땄어요.",
  "She made a snowman in winter.": "그녀는 겨울에 눈사람을 만들었어요.",
  "They ate watermelon yesterday.": "그들은 어제 수박을 먹었어요.",
  "My dad cleaned leaves outside.": "우리 아빠는 밖에서 나뭇잎을 치웠어요.",
  "Did you feel warm winds?": "따뜻한 바람을 느꼈니?",
  "We drank hot tea together.": "우리는 함께 따뜻한 차를 마셨어요.",
  "It snowed heavily on Monday.": "월요일에 눈이 많이 내렸어요.",
  "I saw yellow leaves fall down.": "나는 노란 나뭇잎이 떨어지는 것을 봤어요.",
  "Put on your warm jacket.": "따뜻한 재킷을 입으세요.",
  "This blue shirt is too big.": "이 파란 셔츠는 너무 커요.",
  "Whose yellow cap is that?": "저 노란 모자는 누구 것이니?",
  "She wants to wear a skirt.": "그녀는 치마를 입고 싶어 해요.",
  "Hang your coat in the closet.": "외투를 옷장에 걸어 두세요.",
  "These brown boots are nice.": "이 갈색 부츠는 멋져요.",
  "Try on that green sweater.": "저 초록색 스웨터를 입어 보세요.",
  "Where did you buy the socks?": "그 양말을 어디에서 샀니?",
  "His black pants look neat.": "그의 검은 바지가 깔끔해 보여요.",
  "I need a red winter scarf.": "나는 빨간 겨울 목도리가 필요해요.",
  "My left foot hurts today.": "오늘은 왼발이 아파요.",
  "Have a good day at school!": "학교에서 즐거운 하루 보내세요!",
  "This small box is made of wood.": "이 작은 상자는 나무로 만들었어요.",
  "She needs wool for a new hat.": "그녀는 새 모자를 만들 털실이 필요해요.",
  "Put on your hood in the rain.": "비가 올 때 모자를 쓰세요.",
  "Where is the hook for my coat?": "내 외투를 걸 고리는 어디에 있나요?",
  "We took a bus to the zoo.": "우리는 버스를 타고 동물원에 갔어요.",
  "A boy stood by the door.": "한 남자아이가 문 옆에 서 있었어요.",
  "Can we eat lunch at noon?": "우리 낮 열두 시에 점심을 먹어도 될까요?",
  "There is a frog in my boot!": "내 장화 안에 개구리가 있어요!",
  "The cow eats grass near the field.": "소가 들판 근처에서 풀을 먹어요.",
  "How do you play this game?": "이 게임은 어떻게 하나요?",
  "We can start the race now.": "우리는 지금 경주를 시작할 수 있어요.",
  "Please put the ball down.": "공을 내려놓아 주세요.",
  "There is a pool in our town.": "우리 마을에는 수영장이 있어요.",
  "Are these brown shoes yours?": "이 갈색 신발은 네 것이니?",
  "This flower is for you.": "이 꽃은 너를 위한 거예요.",
  "Take a shower after the game.": "경기가 끝난 뒤에 샤워하세요.",
  "A big crowd is watching the race.": "많은 사람들이 경주를 보고 있어요.",
  "Can you run around the tree?": "나무 주위를 달릴 수 있니?",
  "Where is my little toy car?": "내 작은 장난감 자동차는 어디에 있니?",
  "What a funny hat that boy has!": "저 남자아이의 모자가 정말 재미있게 생겼네요!",
  "She jumped for joy at the news.": "그녀는 그 소식을 듣고 기뻐서 뛰었어요.",
  "Did you enjoy your lunch today?": "오늘 점심 맛있게 먹었니?",
  "The king wears a royal coat.": "왕은 왕의 멋진 옷을 입어요.",
  "My dog is a very loyal friend.": "내 개는 나를 잘 따르는 친구예요.",
  "A fire can destroy many trees.": "불이 나면 많은 나무가 타 없어질 수 있어요.",
  "We saw a cowboy on his horse.": "우리는 말을 탄 카우보이를 봤어요.",
  "The boy can ride a bike.": "그 남자아이는 자전거를 탈 수 있어요.",
  "I enjoy playing with my dog.": "나는 내 개와 노는 것을 좋아해요.",
  "Please write a letter to your friend.": "친구에게 편지를 써 보세요.",
  "Do you have a tennis ball?": "테니스공이 있니?",
  "We had fish for dinner.": "우리는 저녁으로 생선을 먹었어요.",
  "My father wants some coffee.": "우리 아빠는 커피를 좀 마시고 싶어 해요.",
  "Who won the soccer game?": "누가 축구 경기에서 이겼나요?",
  "A puppy is under the chair.": "강아지 한 마리가 의자 아래에 있어요.",
  "How small that kitten is!": "저 아기 고양이는 정말 작네요!",
  "Stop running in the classroom.": "교실에서 뛰지 마세요.",
  "Swimming makes me happy.": "수영을 하면 나는 기분이 좋아요.",
  "Why are you sitting on my bag?": "왜 내 가방 위에 앉아 있니?",
  "Can you help me with this puzzle?": "이 퍼즐을 푸는 것을 도와줄 수 있니?",
  "I cycle to school with my friends.": "나는 친구들과 자전거를 타고 학교에 가요.",
  "A blue marble is under my desk.": "파란 구슬이 내 책상 아래에 있어요.",
  "The game starts when I blow my whistle.": "내가 호루라기를 불면 게임이 시작돼요.",
  "Draw a big circle around the star.": "별 주위에 큰 동그라미를 그리세요.",
  "There is a candle on the cake.": "케이크 위에 초가 있어요.",
  "This puzzle is fun to do.": "이 퍼즐은 풀면 재미있어요.",
  "We cycle in the park after school.": "우리는 방과 후에 공원에서 자전거를 타요.",
  "Put the red marble in the box.": "빨간 구슬을 상자 안에 넣으세요.",
  "We sit in a circle and sing.": "우리는 둥글게 앉아 노래해요.",
  "This song makes me happy.": "이 노래를 들으면 기분이 좋아져요.",
  "I feel calm with music.": "음악을 들으면 마음이 편안해져요.",
  "Her song makes us smile.": "그녀의 노래를 들으면 우리는 웃게 돼요.",
  "We are excited to sing.": "우리는 노래할 생각에 신이 나요.",
  "Music makes my heart warm.": "음악을 들으면 마음이 따뜻해져요.",
  "That song sounds sad to me.": "그 노래는 나에게 슬프게 들려요.",
  "I am glad to hear this song.": "이 노래를 들으니 기뻐요.",
  "Singing makes him feel good.": "노래를 부르면 그는 기분이 좋아져요.",
  "The music makes her excited.": "그 음악을 들으면 그녀는 신이 나요.",
  "We feel happy when we sing.": "우리는 노래할 때 행복해요.",
  "A rabbit runs in the field.": "토끼 한 마리가 들판에서 달려요.",
  "Birds sing in the green trees.": "새들이 푸른 나무에서 노래해요.",
  "A frog jumps by the river.": "개구리 한 마리가 강가에서 뛰어요.",
  "The bear walks in the forest.": "곰이 숲속을 걸어요.",
  "Fish swim under the water.": "물고기들이 물속에서 헤엄쳐요.",
  "A butterfly sits on a flower.": "나비 한 마리가 꽃 위에 앉아 있어요.",
  "The duck swims across the lake.": "오리가 호수를 가로질러 헤엄쳐요.",
  "Bees fly around the flowers.": "벌들이 꽃 주위를 날아다녀요.",
  "A fox lives near the mountain.": "여우 한 마리가 산 근처에 살아요.",
  "The turtle rests by the pond.": "거북이가 연못가에서 쉬어요.",
  "I cleaned my small room.": "나는 내 작은 방을 청소했어요.",
  "Dad cooked dinner at home.": "아빠는 집에서 저녁을 만들었어요.",
  "She opened the front door.": "그녀는 현관문을 열었어요.",
  "We washed dirty dishes.": "우리는 더러운 그릇을 씻었어요.",
  "He closed the living room window.": "그는 거실 창문을 닫았어요.",
  "Grandma rested on the soft sofa.": "할머니는 푹신한 소파에서 쉬셨어요.",
  "My brother planted seeds in the yard.": "내 남자 형제는 마당에 씨앗을 심었어요.",
  "They watched television together.": "그들은 함께 텔레비전을 봤어요.",
  "The cute puppy jumped on the bed.": "귀여운 강아지가 침대 위로 뛰어올랐어요.",
  "Mom fixed the broken chair.": "엄마는 망가진 의자를 고쳤어요.",
  "A brown hare has soft white hair.": "갈색 산토끼는 부드러운 흰 털이 있어요.",
  "The big black bear has bare feet.": "크고 검은 곰은 맨발이에요.",
  "I can hear small birds right here.": "바로 여기에서 작은 새들의 소리를 들을 수 있어요.",
  "A sunny day brings our bright sun.": "맑은 날에는 밝은 해가 비쳐요.",
  "There is their wooden house in nature.": "자연 속에 그들의 나무집이 있어요.",
  "Fresh green pear trees grow in a pair.": "싱싱한 초록 배나무 두 그루가 나란히 자라요.",
  "Leaves fall through the whole hole.": "나뭇잎들이 큰 구멍을 지나 떨어져요.",
  "Deer ran to my dear old garden.": "사슴들이 내가 아끼는 오래된 정원으로 달려갔어요.",
  "Night brings a brave, shining knight.": "밤이 되자 용감하고 빛나는 기사가 나타나요.",
  "Sweet flower honey comes from flour.": "달콤한 꽃꿀은 밀가루에서 나와요.",
  "Can I have some warm milk, please?": "따뜻한 우유를 좀 마셔도 될까요?",
  "Sure, try this sweet red apple.": "물론이죠, 이 달콤한 빨간 사과를 먹어 보세요.",
  "May I eat another piece of cake?": "케이크 한 조각을 더 먹어도 될까요?",
  "Please pass the salt and pepper.": "소금과 후추를 건네주세요.",
  "Could you cut the fresh bread?": "갓 만든 빵을 잘라 주시겠어요?",
  "Yes, you may drink cold juice.": "네, 차가운 주스를 마셔도 돼요.",
  "Would you bring four clean forks?": "깨끗한 포크 네 개를 가져다주시겠어요?",
  "Of course, enjoy your hot soup.": "물론이죠, 따뜻한 수프를 맛있게 드세요.",
  "No, do not touch the spicy pizza.": "안 돼요, 매운 피자에 손대지 마세요.",
  "May I choose lunch from the menu?": "메뉴에서 점심을 골라도 될까요?",
  "The park is bigger than the yard.": "공원은 마당보다 더 커요.",
  "My school is closer than yours.": "우리 학교가 네 학교보다 더 가까워요.",
  "This street is wider.": "이 길은 더 넓어요.",
  "Our library is quieter.": "우리 도서관은 더 조용해요.",
  "Their town is smaller than ours.": "그들의 마을은 우리 마을보다 더 작아요.",
  "The hill is higher than that tree.": "언덕은 저 나무보다 더 높아요.",
  "That store is newer than this one.": "저 가게는 이 가게보다 더 새로워요.",
  "Which bridge is longer?": "어느 다리가 더 길어요?",
  "His house is taller than mine.": "그의 집은 우리 집보다 더 높아요.",
  "A bus is faster than a bike.": "버스는 자전거보다 더 빨라요.",
  "They smile because they feel happy.": "그들은 기분이 좋아서 웃어요.",
  "Why are you looking so upset today?": "오늘 왜 그렇게 속상해 보여요?",
  "He cries because he feels very sad.": "그는 너무 슬퍼서 울어요.",
  "We shout because we are excited.": "우리는 신이 나서 소리쳐요.",
  "She stays inside because she is scared.": "그녀는 무서워서 안에 있어요.",
  "I jump up because of pure joy.": "나는 너무 기뻐서 펄쩍 뛰어요.",
  "The boy sleeps because he is tired.": "그 남자아이는 피곤해서 자요.",
  "Why is the little child angry now?": "그 어린아이는 지금 왜 화가 났어요?",
  "Cheer loudly because we are proud.": "우리는 자랑스러우니 크게 응원해요.",
  "She feels lonely because nobody came.": "아무도 오지 않아서 그녀는 외로워요.",
  "Let's paint with bright colors.": "밝은 색으로 색칠해 봐요.",
  "Shall we choose the blue paper?": "파란색 종이를 고를까요?",
  "Why don't we use red crayons?": "빨간색 크레용을 쓰는 게 어때요?",
  "How about mixing yellow and green?": "노란색과 초록색을 섞어 보는 게 어때요?",
  "What about drawing a purple sky?": "보라색 하늘을 그려 보는 게 어때요?",
  "Would you like some orange juice?": "오렌지 주스 좀 마실래요?",
  "Let us make a black mask.": "검은색 가면을 만들어요.",
  "Can we wear pink shirts today?": "오늘 분홍색 셔츠를 입어도 될까요?",
  "Why not buy a brown ribbon?": "갈색 리본을 사는 게 어때요?",
  "Shall we find gray stones?": "회색 돌을 찾아볼까요?",
  "I visited my grandpa last week.": "나는 지난주에 할아버지를 찾아뵈었어요.",
  "We stayed at a quiet hotel.": "우리는 조용한 호텔에서 묵었어요.",
  "He bought tickets for the train.": "그는 기차표를 샀어요.",
  "She packed her small bag early.": "그녀는 작은 가방을 일찍 챙겼어요.",
  "They took pictures near the lake.": "그들은 호수 근처에서 사진을 찍었어요.",
  "My family rode a tour bus.": "우리 가족은 관광버스를 탔어요.",
  "Did you enjoy your long trip?": "긴 여행이 즐거웠나요?",
  "We climbed a tall mountain.": "우리는 높은 산에 올라갔어요.",
  "The airplane arrived on time.": "비행기가 제시간에 도착했어요.",
  "Uncle went camping in the woods.": "삼촌은 숲으로 캠핑을 갔어요.",
  "I wake up early every day.": "나는 매일 일찍 일어나요.",
  "Brush your teeth after meals.": "밥을 먹은 뒤에 이를 닦으세요.",
  "He eats breakfast at seven.": "그는 일곱 시에 아침을 먹어요.",
  "We walk to school together.": "우리는 함께 걸어서 학교에 가요.",
  "She does her homework now.": "그녀는 지금 숙제를 해요.",
  "Wash your hands before lunch.": "점심을 먹기 전에 손을 씻으세요.",
  "They play soccer after class.": "그들은 수업이 끝난 뒤에 축구를 해요.",
  "My brother feeds the puppy.": "내 남자 형제는 강아지에게 먹이를 줘요.",
  "I read books in the evening.": "나는 저녁에 책을 읽어요.",
  "Help your dad clean the room.": "아빠가 방을 청소하는 것을 도와주세요.",
  "berries": "열매들",
  "candies": "사탕들",
  "cherries": "체리들",
  "fries": "감자튀김",
  "jellies": "젤리들",
  "bakeries": "빵집들",
  "groceries": "식료품",
  "cookies": "쿠키들",
  "spices": "향신료들",
  "carries": "나른다",
  "light": "빛",
  "night": "밤",
  "right": "오른쪽",
  "bright": "밝은",
  "sight": "광경",
  "flight": "비행",
  "straight": "곧은",
  "daughter": "딸",
  "bought": "샀다",
  "brought": "가져왔다",
  "listen": "듣다",
  "often": "자주",
  "fasten": "매다",
  "soften": "부드럽게 하다",
  "castle": "성",
  "whistle": "휘파람",
  "wrestle": "씨름하다",
  "bustle": "바삐 움직이다",
  "rustle": "바스락거리다",
  "honest": "정직한",
  "it's": "그것은 ~이다",
  "don't": "~하지 않는다",
  "can't": "~할 수 없다",
  "you're": "너는 ~이다",
  "he's": "그는 ~이다",
  "she's": "그녀는 ~이다",
  "we're": "우리는 ~이다",
  "they're": "그들은 ~이다",
  "isn't": "~이 아니다",
  "aren't": "~이 아니다",
  "fast": "빠른",
  "early": "일찍",
  "late": "늦은",
  "far": "먼",
  "near": "가까운",
  "cheap": "싼",
  "expensive": "비싼",
  "safe": "안전한",
  "dangerous": "위험한",
  "busy": "바쁜",
  "quiet": "조용한",
  "o'clock": "~시",
  "write": "쓰다",
  "watch": "보다",
  "study": "공부하다",
  "Today is colder than yesterday.": "오늘은 어제보다 더 추워요.",
  "It becomes darker outside.": "밖이 점점 어두워져요.",
  "The sky looks clearer today.": "오늘은 하늘이 더 맑아 보여요.",
  "Tomorrow will be warmer.": "내일은 더 따뜻할 거예요.",
  "Winter nights are longer.": "겨울에는 밤이 더 길어요.",
  "Spring days are brighter.": "봄에는 낮이 더 밝아요.",
  "The air feels cooler here.": "여기는 공기가 더 시원하게 느껴져요.",
  "This winter feels drier.": "이번 겨울은 더 건조하게 느껴져요.",
  "The rain gets heavier soon.": "곧 비가 더 세게 내려요.",
  "Fall weather is nicer.": "가을 날씨가 더 좋아요.",
  "He has the longest arms.": "그는 팔이 가장 길어요.",
  "My left foot is the biggest.": "내 왼발이 가장 커요.",
  "Her hair is the darkest.": "그녀의 머리카락이 가장 어두워요.",
  "You have the strongest legs.": "네 다리가 가장 튼튼해요.",
  "This is the shortest finger.": "이 손가락이 가장 짧아요.",
  "The baby has the smallest nose.": "그 아기는 코가 가장 작아요.",
  "His neck looks the thickest.": "그의 목이 가장 굵어 보여요.",
  "She has the widest smile.": "그녀가 가장 활짝 웃어요.",
  "My right hand is the warmest.": "내 오른손이 가장 따뜻해요.",
  "His face turned the reddest.": "그의 얼굴이 가장 빨개졌어요.",
  "Why do you like spring?": "왜 봄을 좋아해요?",
  "Because warm flowers bloom.": "따뜻한 날에 꽃이 피기 때문이에요.",
  "Why is summer your favorite?": "왜 여름을 가장 좋아해요?",
  "I can swim in the cool river.": "시원한 강에서 수영할 수 있어요.",
  "Why does he love fall days?": "그는 왜 가을날을 좋아해요?",
  "Because sweet apples are ripe.": "달콤한 사과가 익기 때문이에요.",
  "Why do they wait for winter?": "그들은 왜 겨울을 기다려요?",
  "We want to build a snowman.": "우리는 눈사람을 만들고 싶어요.",
  "Why are you putting on a coat?": "왜 코트를 입고 있어요?",
  "Why does she smile today?": "그녀는 오늘 왜 웃어요?",
  "How is this shirt?": "이 셔츠 어때요?",
  "How is your new cap?": "새 모자는 어때요?",
  "How do you like my coat?": "내 코트 어때요?",
  "How is the blue dress?": "파란색 원피스 어때요?",
  "How do these shoes look?": "이 신발 어때 보여요?",
  "How is that yellow skirt?": "저 노란색 치마 어때요?",
  "How do you like this jacket?": "이 재킷 어때요?",
  "How does my hat look?": "내 모자 어때 보여요?",
  "How is your green sweater?": "네 초록색 스웨터 어때요?",
  "How do you like these pants?": "이 바지 어때요?",
  "First, I eat with my family.": "먼저, 나는 가족과 함께 밥을 먹어요.",
  "Then, I help my mother cook.": "그다음, 나는 엄마가 요리하는 것을 도와요.",
  "Next, my brother washes dishes.": "다음으로, 내 남자 형제는 설거지를 해요.",
  "After that, we clean the house.": "그 후에, 우리는 집을 청소해요.",
  "Later, my sister feeds the dog.": "나중에, 내 여자 형제는 개에게 먹이를 줘요.",
  "Before dinner, Dad comes home.": "저녁을 먹기 전에 아빠가 집에 와요.",
  "After dinner, we talk together.": "저녁을 먹은 뒤에 우리는 함께 이야기해요.",
  "In the evening, Mom reads a book.": "저녁에 엄마는 책을 읽어요.",
  "At night, I play with my brother.": "밤에 나는 남자 형제와 함께 놀아요.",
  "Before bed, we brush our teeth.": "자기 전에 우리는 이를 닦아요.",
  "I will play soccer tomorrow.": "나는 내일 축구를 할 거예요.",
  "We will practice baseball after school.": "우리는 방과 후에 야구 연습을 할 거예요.",
  "I'm going to swim this weekend.": "나는 이번 주말에 수영할 거예요.",
  "My team will play basketball soon.": "우리 팀은 곧 농구를 할 거예요.",
  "I'll ride my bike in the afternoon.": "나는 오후에 자전거를 탈 거예요.",
  "We're going to run in the park.": "우리는 공원에서 달릴 거예요.",
  "Next week, I will play badminton.": "나는 다음 주에 배드민턴을 칠 거예요.",
  "After lunch, we'll play table tennis.": "우리는 점심을 먹은 뒤에 탁구를 칠 거예요.",
  "On Saturday, I will practice skating.": "나는 토요일에 스케이트 연습을 할 거예요.",
  "Tomorrow, we'll jump rope together.": "우리는 내일 함께 줄넘기를 할 거예요.",
  "Put this teddy bear into the box.": "이 곰 인형을 상자 안에 넣으세요.",
  "Look at that cute toy plane!": "저 귀여운 장난감 비행기를 보세요!",
  "I like playing with wooden blocks.": "나는 나무 블록을 가지고 노는 것을 좋아해요.",
  "Do you want to share your doll?": "네 인형을 함께 가지고 놀래요?",
  "Can he fix the broken robot car?": "그는 고장 난 로봇 자동차를 고칠 수 있나요?",
  "Where did you buy that green puzzle?": "저 초록색 퍼즐을 어디에서 샀어요?",
  "Fly the colorful kite outside.": "밖에서 알록달록한 연을 날리세요.",
  "This game is very exciting to me.": "이 게임은 나에게 정말 신나요.",
  "Whose little puppet is on the chair?": "의자 위의 작은 손 인형은 누구 것인가요?",
  "We love making paper airplanes.": "우리는 종이비행기 만들기를 정말 좋아해요.",
  "thief": "도둑",
  "niece": "조카딸",
  "brief": "짧은",
  "tie": "넥타이",
  "pie": "파이",
  "shield": "방패",
  "neighbor": "이웃",
  "weight": "무게",
  "receive": "받다",
  "Please read these stories to me.": "이 이야기들을 나에게 읽어 주세요.",
  "We play fun games at parties.": "우리는 파티에서 재미있는 게임을 해요.",
  "What are your favorite hobbies?": "가장 좋아하는 취미는 무엇인가요?",
  "School activities start after lunch.": "학교 활동은 점심을 먹은 뒤에 시작해요.",
  "My sister writes in her diaries.": "내 여자 형제는 일기장에 글을 써요.",
  "Many countries have cold winters.": "많은 나라에서는 겨울이 추워요.",
  "Are these cities near the sea?": "이 도시들은 바다 가까이에 있나요?",
  "Big families need big tables.": "식구가 많은 가족은 큰 식탁이 필요해요.",
  "The babies are sleeping now.": "아기들이 지금 자고 있어요.",
  "Look at the puppies under the tree!": "나무 아래에 있는 강아지들을 보세요!",
  "We can sing a song tonight.": "우리는 오늘 밤 노래를 부를 수 있어요.",
  "It might rain after lunch.": "점심을 먹은 뒤에 비가 올지도 몰라요.",
  "These shoes are too tight.": "이 신발은 너무 꽉 끼어요.",
  "I let out a long sigh.": "나는 길게 한숨을 쉬었어요.",
  "Please do not fight with your sister.": "여자 형제와 싸우지 마세요.",
  "There are eight eggs in the box.": "상자 안에 달걀이 여덟 개 있어요.",
  "I might read a book tonight.": "나는 오늘 밤 책을 읽을지도 몰라요.",
  "Eight birds sat on the fence.": "새 여덟 마리가 울타리에 앉았어요.",
  "She gave a soft sigh and smiled.": "그녀는 살며시 한숨을 쉬고 웃었어요.",
  "The lid on this jar is too tight.": "이 병의 뚜껑이 너무 꽉 잠겨 있어요.",
  "A rhino eats grass by the river.": "코뿔소가 강가에서 풀을 먹어요.",
  "Your white shirt looks very clean.": "네 흰 셔츠가 아주 깨끗해 보여요.",
  "Look at that whale in the sea!": "바다에 있는 저 고래를 보세요!",
  "The front wheel will not turn.": "앞바퀴가 돌아가지 않아요.",
  "Which animal has a long neck?": "어떤 동물이 목이 긴가요?",
  "Where did my little dog go?": "내 작은 강아지는 어디로 갔나요?",
  "Tell me what you want for lunch.": "점심으로 무엇을 먹고 싶은지 말해 주세요.",
  "When it rains, we play inside.": "비가 오면 우리는 안에서 놀아요.",
  "The white cat is on the bed.": "흰 고양이가 침대 위에 있어요.",
  "A whale can swim very fast.": "고래는 아주 빠르게 헤엄칠 수 있어요.",
  "That's my bag under the desk.": "책상 아래에 있는 저것은 내 가방이에요.",
  "What's for dinner this evening?": "오늘 저녁은 뭐예요?",
  "There's a bird in the tree.": "나무에 새 한 마리가 있어요.",
  "Let's wash our hands before lunch.": "점심을 먹기 전에 손을 씻어요.",
  "I'll help you carry this box.": "이 상자를 나르는 것을 도와줄게요.",
  "I think you'll like this game.": "네가 이 게임을 좋아할 것 같아요.",
  "After school, he'll ride his bike.": "그는 방과 후에 자전거를 탈 거예요.",
  "At home, she'll read her new book.": "그녀는 집에서 새 책을 읽을 거예요.",
  "If we hurry, we'll catch the bus.": "서두르면 우리는 버스를 탈 수 있을 거예요.",
  "When the bell rings, they'll stop running.": "종이 울리면 그들은 달리기를 멈출 거예요.",
  "I eat bread for breakfast.": "나는 아침으로 빵을 먹어요.",
  "Would you like some juice?": "주스 좀 마실래요?",
  "There is fruit on the table.": "탁자 위에 과일이 있어요.",
  "Please put some sugar in my tea.": "내 차에 설탕을 조금 넣어 주세요.",
  "This cheese looks like a star.": "이 치즈는 별처럼 생겼어요.",
  "Can you cut the tomato in half?": "토마토를 반으로 잘라 줄 수 있나요?",
  "A hot potato fell off my plate.": "뜨거운 감자가 내 접시에서 떨어졌어요.",
  "The onion makes my eyes hurt.": "양파 때문에 눈이 아파요.",
  "We need butter to make cookies.": "쿠키를 만들려면 버터가 필요해요.",
  "Your rabbit is eating a carrot.": "네 토끼가 당근을 먹고 있어요.",
  "My town is smaller than yours.": "우리 동네는 너희 동네보다 더 작아요.",
  "The library is taller than my house.": "도서관은 우리 집보다 더 높아요.",
  "This park is cleaner than that one.": "이 공원은 저 공원보다 더 깨끗해요.",
  "Our new bridge is wider.": "우리의 새 다리는 더 넓어요.",
  "The market is busier on Sundays.": "시장은 일요일에 더 붐벼요.",
  "That tower is higher than the school.": "저 탑은 학교보다 더 높아요.",
  "Main Street is safer for kids.": "큰길이 아이들에게 더 안전해요.",
  "The village road looks older.": "마을 길이 더 오래되어 보여요.",
  "This hill is steeper to climb.": "이 언덕은 올라가기가 더 가팔라요.",
  "The bus station is nearer now.": "이제 버스 정류장이 더 가까워요.",
  "Today was the happiest day.": "오늘이 가장 행복한 날이었어요.",
  "I felt the proudest today.": "오늘 가장 자랑스러웠어요.",
  "She is the bravest girl.": "그녀는 가장 용감한 여자아이예요.",
  "This was the saddest movie.": "이 영화가 가장 슬펐어요.",
  "He looked the angriest then.": "그때 그가 가장 화나 보였어요.",
  "We were the calmest here.": "여기서 우리가 가장 차분했어요.",
  "The baby was the sweetest.": "그 아기가 가장 사랑스러웠어요.",
  "That boy seems the boldest.": "저 남자아이가 가장 씩씩해 보여요.",
  "You looked the fittest now.": "지금 네가 가장 건강해 보여요.",
  "He became the maddest friend.": "그가 가장 화난 친구가 되었어요.",
  "Who is wearing a red cap?": "누가 빨간 모자를 쓰고 있나요?",
  "She has a bright yellow bag.": "그녀는 밝은 노란색 가방을 가지고 있어요.",
  "Who likes the green shirt?": "누가 초록색 셔츠를 좋아하나요?",
  "The boy in blue shoes is Tim.": "파란 신발을 신은 남자아이는 팀이에요.",
  "Who is holding purple paint?": "누가 보라색 물감을 들고 있나요?",
  "He chooses the orange crayon.": "그는 주황색 크레용을 골라요.",
  "Who painted this pink flower?": "누가 이 분홍색 꽃을 그렸나요?",
  "Who has brown hair today?": "오늘 누가 갈색 머리인가요?",
  "My brother wears black pants.": "내 남자 형제는 검은색 바지를 입어요.",
  "Who bought the colorful coat?": "누가 알록달록한 코트를 샀나요?",
  "Why do you visit the island?": "왜 그 섬에 가요?",
  "Because I want to see the sea.": "바다를 보고 싶기 때문이에요.",
  "Why are we packing our bags?": "우리는 왜 가방을 챙기고 있나요?",
  "Let's take a train to the camp.": "기차를 타고 캠프에 가요.",
  "Why does he go to the museum?": "그는 왜 박물관에 가요?",
  "He loves seeing old airplanes.": "그는 오래된 비행기 보는 것을 아주 좋아해요.",
  "Why do they ride the bus now?": "그들은 왜 지금 버스를 타나요?",
  "We need to reach the airport.": "우리는 공항에 가야 해요.",
  "Why is she buying a big tent?": "그녀는 왜 큰 텐트를 사고 있나요?",
  "Because my family goes camping.": "우리 가족이 캠핑을 가기 때문이에요.",
  "How do you go to school?": "학교에 어떻게 가나요?",
  "How do you make breakfast?": "아침밥을 어떻게 만드나요?",
  "How do you clean your room?": "방을 어떻게 청소하나요?",
  "How do you get home?": "집에 어떻게 가나요?",
  "How do you help your family?": "가족을 어떻게 도와주나요?",
  "How do you study English?": "영어를 어떻게 공부하나요?",
  "How do you spend your weekend?": "주말을 어떻게 보내나요?",
  "How do you start your day?": "하루를 어떻게 시작하나요?",
  "How do you wash your hands?": "손을 어떻게 씻나요?",
  "How do you make your bed?": "침대를 어떻게 정리하나요?",
  "Early today, the sun is bright.": "오늘 아침 일찍 해가 밝게 빛나요.",
  "Soon, clouds come into the sky.": "곧 하늘에 구름이 나타나요.",
  "By noon, the weather gets warm.": "낮이 되면 날씨가 따뜻해져요.",
  "This afternoon, the wind blows hard.": "오늘 오후에는 바람이 세게 불어요.",
  "A little later, rain starts to fall.": "조금 뒤에 비가 내리기 시작해요.",
  "Toward evening, the air gets cool.": "저녁이 되면서 공기가 시원해져요.",
  "As it gets dark, they return inside.": "날이 어두워지자 그들은 안으로 돌아와요.",
  "On a sunny morning, birds sing.": "햇살 좋은 아침에 새들이 노래해요.",
  "During a hot day, kids drink water.": "더운 날에는 아이들이 물을 마셔요.",
  "On a cold evening, people wear coats.": "추운 저녁에는 사람들이 코트를 입어요.",
  "I will wash my hands before dinner.": "나는 저녁을 먹기 전에 손을 씻을 거예요.",
  "I'm going to brush my teeth tonight.": "나는 오늘 밤 이를 닦을 거예요.",
  "Tomorrow, I will exercise my legs.": "나는 내일 다리 운동을 할 거예요.",
  "I'll rest my eyes after reading.": "나는 책을 읽은 뒤에 눈을 쉴 거예요.",
  "We will stretch our arms in class.": "우리는 수업 시간에 팔을 쭉 뻗을 거예요.",
  "I'm going to wash my face soon.": "나는 곧 세수할 거예요.",
  "Later, I will comb my hair.": "나는 나중에 머리를 빗을 거예요.",
  "After breakfast, I'll clean my ears.": "나는 아침을 먹은 뒤에 귀를 닦을 거예요.",
  "Tonight, I will take care of my feet.": "나는 오늘 밤 발을 잘 씻고 돌볼 거예요.",
  "Soon, we'll move our shoulders slowly.": "우리는 곧 어깨를 천천히 움직일 거예요.",
  "Open your English textbook now.": "지금 영어 교과서를 펴세요.",
  "Our classroom is on the third floor.": "우리 교실은 3층에 있어요.",
  "Did you finish the science report?": "과학 보고서를 다 썼나요?",
  "Meet me in the school cafeteria.": "학교 식당에서 만나요.",
  "She borrows books from the library.": "그녀는 도서관에서 책을 빌려요.",
  "Write your name with a sharp pencil.": "잘 깎은 연필로 이름을 쓰세요.",
  "Clean the black desk with a wet cloth.": "젖은 천으로 검은색 책상을 닦으세요.",
  "Where did they keep the jump ropes?": "그들은 줄넘기를 어디에 두었나요?",
  "We have art and music every Friday.": "우리는 금요일마다 미술과 음악 수업이 있어요.",
  "Don't run fast in the hallway!": "복도에서 빨리 뛰지 마세요!",
  "action": "행동",
  "station": "역",
  "question": "질문",
  "vacation": "방학",
  "attention": "주의",
  "direction": "방향",
  "education": "교육",
  "mention": "말하다",
  "section": "부분",
  "condition": "상태",
  "unhappy": "행복하지 않은",
  "unusual": "특이한",
  "unknown": "알려지지 않은",
  "unwell": "몸이 안 좋은",
  "unfair": "불공평한",
  "unsafe": "안전하지 않은",
  "unlike": "~와 다른",
  "untrue": "사실이 아닌",
  "rewrite": "다시 쓰다",
  "replay": "다시 하다",
  "classroom": "교실",
  "student": "학생",
  "notebook": "공책",
  "computer": "컴퓨터",
  "calendar": "달력",
  "homework": "숙제",
  "fell": "떨어졌다",
  "blew": "불었다",
  "froze": "얼었다",
  "grew": "자랐다",
  "shone": "빛났다",
  "wore": "입었다",
  "swam": "수영했다",
  "felt": "느꼈다",
  "began": "시작했다",
  "I wore a warm jacket yesterday.": "나는 어제 따뜻한 재킷을 입었어요.",
  "She put on her blue winter coat.": "그녀는 파란색 겨울 코트를 입었어요.",
  "Mom bought a pretty dress for me.": "엄마가 나에게 예쁜 원피스를 사 주셨어요.",
  "He chose brown shoes this morning.": "그는 오늘 아침 갈색 신발을 골랐어요.",
  "They found my lost yellow socks.": "그들은 내가 잃어버린 노란색 양말을 찾았어요.",
  "My sister took off her wet boots.": "내 여자 형제는 젖은 장화를 벗었어요.",
  "I tore my pants during the game.": "나는 게임을 하다가 바지가 찢어졌어요.",
  "Dad hung his nice shirt in the room.": "아빠는 멋진 셔츠를 방에 걸어 두셨어요.",
  "She blew snow off her warm mittens.": "그녀는 따뜻한 벙어리장갑에 묻은 눈을 불어 털었어요.",
  "We made funny paper hats together.": "우리는 함께 재미있는 종이 모자를 만들었어요.",
  "I will help my mom today.": "나는 오늘 엄마를 도와드릴 거예요.",
  "My dad will cook dinner tonight.": "아빠는 오늘 저녁에 저녁밥을 만드실 거예요.",
  "We will visit my grandma tomorrow.": "우리는 내일 할머니를 찾아뵐 거예요.",
  "My sister will clean her room later.": "내 여자 형제는 나중에 자기 방을 청소할 거예요.",
  "Our family will eat lunch together.": "우리 가족은 함께 점심을 먹을 거예요.",
  "My brother will play with me after school.": "내 남자 형제는 방과 후에 나와 함께 놀 거예요.",
  "I will call my grandpa this evening.": "나는 오늘 저녁에 할아버지께 전화할 거예요.",
  "Mom will read a book with my sister.": "엄마는 내 여자 형제와 함께 책을 읽으실 거예요.",
  "Dad will take us to the park tomorrow.": "아빠는 내일 우리를 공원에 데려가실 거예요.",
  "We will make a cake for my brother.": "우리는 내 남자 형제를 위해 케이크를 만들 거예요.",
  "I am going to play soccer.": "나는 축구를 할 거예요.",
  "We are going to practice baseball.": "우리는 야구 연습을 할 거예요.",
  "He is going to ride his bike.": "그는 자전거를 탈 거예요.",
  "She is going to learn tennis.": "그녀는 테니스를 배울 거예요.",
  "They are going to watch a basketball game.": "그들은 농구 경기를 볼 거예요.",
  "My brother is going to swim today.": "내 남자 형제는 오늘 수영할 거예요.",
  "Our team is going to win the game.": "우리 팀은 경기에서 이길 거예요.",
  "The boys are going to play badminton.": "남자아이들은 배드민턴을 칠 거예요.",
  "The girls are going to jump rope.": "여자아이들은 줄넘기를 할 거예요.",
  "My friend is going to try table tennis.": "내 친구는 탁구를 해 볼 거예요.",
  "I like the doll because it is cute.": "나는 그 인형이 귀여워서 좋아해요.",
  "The robot is small but it can move.": "그 로봇은 작지만 움직일 수 있어요.",
  "I have a ball and my brother has a kite.": "나는 공이 있고 내 남자 형제는 연이 있어요.",
  "This train is old but I still like it.": "이 기차는 오래되었지만 나는 여전히 좋아해요.",
  "She wants the blocks because they are fun.": "그녀는 블록이 재미있어서 갖고 싶어 해요.",
  "My toy car is red and it runs fast.": "내 장난감 자동차는 빨간색이고 빠르게 달려요.",
  "He likes the plane but he wants the boat.": "그는 비행기를 좋아하지만 배를 갖고 싶어 해요.",
  "We play with cards because they are easy.": "우리는 카드가 쉬워서 가지고 놀아요.",
  "That bear is soft and it has big eyes.": "저 곰 인형은 부드럽고 눈이 커요.",
  "The puzzle is hard but I want to try it.": "그 퍼즐은 어렵지만 나는 해 보고 싶어요.",
  "I want to be a teacher like my friend.": "나는 내 친구처럼 선생님이 되고 싶어요.",
  "My best friend wants to be a doctor.": "내 가장 친한 친구는 의사가 되고 싶어 해요.",
  "She wants to be a cook when she grows up.": "그녀는 커서 요리사가 되고 싶어 해요.",
  "He hopes to be a great soccer player.": "그는 훌륭한 축구 선수가 되고 싶어 해요.",
  "We want to be kind teachers someday.": "우리는 언젠가 친절한 선생님이 되고 싶어요.",
  "My classmate wants to be an artist.": "내 반 친구는 화가가 되고 싶어 해요.",
  "They hope to be good singers in the future.": "그들은 나중에 훌륭한 가수가 되고 싶어 해요.",
  "You can be a writer if you like stories.": "이야기를 좋아한다면 작가가 될 수 있어요.",
  "Her friend wants to be a police officer.": "그녀의 친구는 경찰관이 되고 싶어 해요.",
  "His dream is to be a good basketball player.": "그의 꿈은 훌륭한 농구 선수가 되는 거예요.",
  "Let's play soccer after school.": "방과 후에 축구를 해요.",
  "How about drawing a picture together?": "함께 그림을 그리는 게 어때요?",
  "Why don't we read a book today?": "오늘 책을 읽는 게 어때요?",
  "Let's listen to music after dinner.": "저녁을 먹은 뒤에 음악을 들어요.",
  "How about riding our bikes in the park?": "공원에서 자전거를 타는 게 어때요?",
  "Why don't we take some pictures outside?": "밖에서 사진을 찍는 게 어때요?",
  "Let's make a paper plane this afternoon.": "오늘 오후에 종이비행기를 만들어요.",
  "How about playing the piano for fun?": "재미로 피아노를 쳐 보는 게 어때요?",
  "Why don't we watch a movie at home?": "집에서 영화를 보는 게 어때요?",
  "Let's dance to this song together.": "이 노래에 맞춰 함께 춤춰요.",
  "A piano is an instrument with many keys.": "피아노는 건반이 많은 악기예요.",
  "A drum is an instrument you hit with your hands.": "드럼은 손으로 두드려 연주하는 악기예요.",
  "A guitar is an instrument with strings.": "기타는 줄이 있는 악기예요.",
  "A song is music that people sing.": "노래는 사람들이 목소리로 부르는 음악이에요.",
  "A singer is a person who sings songs.": "가수는 노래를 부르는 사람이에요.",
  "A band is a group that plays music together.": "밴드는 함께 음악을 연주하는 모임이에요.",
  "A flute is an instrument you play by blowing.": "플루트는 입으로 불어서 연주하는 악기예요.",
  "A concert is a place to hear live music.": "콘서트는 직접 연주하는 음악을 듣는 곳이에요.",
  "A note is a sign used to write music.": "음표는 음악을 적을 때 쓰는 표시예요.",
  "A violin is a small instrument with strings.": "바이올린은 줄이 있는 작은 악기예요.",
  "A tiger is bigger than a cat.": "호랑이는 고양이보다 더 커요.",
  "An elephant is heavier than a horse.": "코끼리는 말보다 더 무거워요.",
  "A rabbit is smaller than a dog.": "토끼는 개보다 더 작아요.",
  "A giraffe is taller than a zebra.": "기린은 얼룩말보다 더 키가 커요.",
  "A turtle is slower than a mouse.": "거북이는 쥐보다 더 느려요.",
  "A cheetah is faster than a lion.": "치타는 사자보다 더 빨라요.",
  "A whale is larger than a dolphin.": "고래는 돌고래보다 더 커요.",
  "A snake is longer than a frog.": "뱀은 개구리보다 더 길어요.",
  "A monkey is smaller than a bear.": "원숭이는 곰보다 더 작아요.",
  "A horse can run faster than a cow.": "말은 소보다 더 빨리 달릴 수 있어요.",
  "I am happy to be home.": "집에 있어서 행복해요.",
  "We feel safe in our house.": "우리는 집에 있으면 안전하다고 느껴요.",
  "Mom is glad to see me.": "엄마는 나를 만나서 기뻐하세요.",
  "Dad looks tired after work.": "아빠는 일을 마치고 나면 피곤해 보여요.",
  "My sister feels sad today.": "내 여자 형제는 오늘 슬퍼해요.",
  "Home makes my heart warm.": "집에 있으면 마음이 따뜻해져요.",
  "I feel sorry about the mess.": "어질러 놓은 것이 미안해요.",
  "Our family is excited tonight.": "우리 가족은 오늘 밤 신이 나요.",
  "Grandma seems pleased with dinner.": "할머니는 저녁 식사가 마음에 드시는 것 같아요.",
  "My brother looks worried now.": "내 남자 형제는 지금 걱정스러워 보여요.",
  "Look at the tall green tree.": "키가 큰 초록색 나무를 보세요.",
  "A gentle wind blows across the hill.": "언덕에 부드러운 바람이 불어요.",
  "Do you hear the river flow?": "강물이 흐르는 소리가 들리나요?",
  "Small birds build a warm nest.": "작은 새들이 따뜻한 둥지를 만들어요.",
  "The bright sun warms the cold earth.": "밝은 햇빛이 차가운 땅을 따뜻하게 해요.",
  "Many fish swim in the deep blue sea.": "많은 물고기가 깊고 푸른 바다에서 헤엄쳐요.",
  "Leaves turn red during cool autumn.": "선선한 가을에는 나뭇잎이 빨갛게 변해요.",
  "Spring brings beautiful wild flowers.": "봄이 오면 아름다운 들꽃이 피어요.",
  "Snow covers the silent high mountains.": "눈이 조용한 높은 산을 덮어요.",
  "We must protect our clean forest.": "우리는 깨끗한 숲을 지켜야 해요.",
  "This shop has a good selection of fruit.": "이 가게에는 여러 가지 좋은 과일이 있어요.",
  "Your cake is a beautiful creation.": "네가 만든 케이크는 아름다운 작품이에요.",
  "We ate rice cakes at the celebration.": "우리는 축하하는 자리에서 떡을 먹었어요.",
  "Food preparation takes time.": "음식을 준비하는 데는 시간이 걸려요.",
  "Her collection of cups is on the shelf.": "그녀가 모은 컵들이 선반 위에 있어요.",
  "Is soup an option for dinner?": "저녁으로 수프를 먹어도 될까요?",
  "Our celebration starts with a big cake.": "우리의 축하는 큰 케이크와 함께 시작해요.",
  "This cake is my own creation.": "이 케이크는 내가 직접 만든 작품이에요.",
  "We have a small collection of bowls.": "우리는 그릇을 조금 모아 두었어요.",
  "Rice is a good option for lunch.": "점심으로 밥을 먹는 것도 좋아요.",
  "I am unable to find the park.": "나는 공원을 찾을 수 없어요.",
  "The map of our town is unclear.": "우리 동네 지도가 알아보기 어려워요.",
  "How unlucky we were to miss the bus!": "버스를 놓치다니 정말 운이 없었어요!",
  "Why is that shop owner so unfriendly?": "저 가게 주인은 왜 그렇게 불친절한가요?",
  "That small mistake seems unimportant now.": "그 작은 실수는 이제 중요하지 않은 것 같아요.",
  "These new shoes feel uncomfortable on my feet.": "이 새 신발은 발이 불편해요.",
  "Let us rebuild the old town bridge.": "마을의 오래된 다리를 다시 지어요.",
  "Can you remake this cake for the party?": "파티를 위해 이 케이크를 다시 만들어 줄 수 있나요?",
  "Please restart the movie after lunch.": "점심을 먹은 뒤에 영화를 처음부터 다시 틀어 주세요.",
  "We can rebuild the small town park.": "우리는 작은 마을 공원을 다시 만들 수 있어요.",
  "careful": "조심하는",
  "careless": "조심성 없는",
  "hopeful": "희망에 찬",
  "hopeless": "희망이 없는",
  "joyful": "기쁜",
  "joyless": "기쁨이 없는",
  "painful": "아픈",
  "painless": "아프지 않은",
  "fearful": "두려워하는",
  "fearless": "두려움 없는",
  "The yellow bus stops here.": "노란색 버스가 여기에 서요.",
  "Would you like an orange?": "오렌지 하나 먹을래요?",
  "She wore a purple hat yesterday.": "그녀는 어제 보라색 모자를 썼어요.",
  "My silver watch is on the desk.": "내 은색 시계가 책상 위에 있어요.",
  "We found a golden key under the bed.": "우리는 침대 아래에서 금색 열쇠를 찾았어요.",
  "These colorful flowers smell so good.": "이 알록달록한 꽃들은 향기가 정말 좋아요.",
  "Can you see the rainbow above us?": "우리 위에 있는 무지개가 보이나요?",
  "Look at the sun shining on the water.": "물 위로 비치는 햇빛을 보세요.",
  "My purple crayon rolled off the table.": "내 보라색 크레용이 탁자에서 굴러 떨어졌어요.",
  "The golden leaves are shining today.": "오늘 금빛 나뭇잎이 반짝이고 있어요.",
  "Yesterday, we went to the beach.": "어제 우리는 바닷가에 갔어요.",
  "Who came with you on the trip?": "누가 너와 함께 여행을 갔나요?",
  "At the lake, she took a picture.": "그녀는 호수에서 사진을 찍었어요.",
  "A small bird flew over our boat.": "작은 새 한 마리가 우리 배 위로 날아갔어요.",
  "After lunch, I rode a bike.": "나는 점심을 먹은 뒤에 자전거를 탔어요.",
  "Mom bought bread for us to share.": "엄마가 우리가 함께 먹을 빵을 사 오셨어요.",
  "We spent the night in a tent.": "우리는 텐트에서 하룻밤을 보냈어요.",
  "Look at the shell I found!": "내가 찾은 조개껍데기를 보세요!",
  "My brother slept while we walked.": "우리가 걷는 동안 내 남자 형제는 잠을 잤어요.",
  "We went to the park by bus.": "우리는 버스를 타고 공원에 갔어요.",
  "I got up early this Sunday.": "나는 이번 일요일에 일찍 일어났어요.",
  "She ate delicious toast for breakfast.": "그녀는 아침으로 맛있는 토스트를 먹었어요.",
  "He drank sweet milk with cookies.": "그는 쿠키와 함께 달콤한 우유를 마셨어요.",
  "We went to the quiet library together.": "우리는 함께 조용한 도서관에 갔어요.",
  "My brother read three comic books.": "내 남자 형제는 만화책 세 권을 읽었어요.",
  "She rode a bicycle in the park.": "그녀는 공원에서 자전거를 탔어요.",
  "They ran across the green field.": "그들은 푸른 들판을 가로질러 달렸어요.",
  "I wrote a secret letter to my friend.": "나는 친구에게 비밀 편지를 썼어요.",
  "Mom spoke kindly to our family.": "엄마는 우리 가족에게 다정하게 말씀하셨어요.",
  "The boy slept late on Saturday.": "그 남자아이는 토요일에 늦게까지 잤어요.",
  "It will rain this afternoon.": "오늘 오후에는 비가 올 거예요.",
  "The sun will come out soon.": "곧 해가 나올 거예요.",
  "We will stay inside on a rainy day.": "우리는 비 오는 날에는 안에 있을 거예요.",
  "I will take my umbrella tomorrow.": "나는 내일 우산을 가져갈 거예요.",
  "The weather will be sunny this weekend.": "이번 주말에는 날씨가 맑을 거예요.",
  "My friend will wear a coat outside.": "내 친구는 밖에서 코트를 입을 거예요.",
  "It will be cold in the morning.": "아침에는 추울 거예요.",
  "We will play outside when it is warm.": "날씨가 따뜻하면 우리는 밖에서 놀 거예요.",
  "I will wear my hat on a hot day.": "나는 더운 날에 모자를 쓸 거예요.",
  "The wind will be strong this evening.": "오늘 저녁에는 바람이 세게 불 거예요.",
  "I am going to wash my hands.": "나는 손을 씻을 거예요.",
  "She is going to brush her teeth.": "그녀는 이를 닦을 거예요.",
  "He is going to open his mouth.": "그는 입을 벌릴 거예요.",
  "We are going to close our eyes.": "우리는 눈을 감을 거예요.",
  "They are going to move their arms.": "그들은 팔을 움직일 거예요.",
  "My sister is going to touch her nose.": "내 여자 형제는 코를 만질 거예요.",
  "The baby is going to lift one foot.": "아기는 한쪽 발을 들어 올릴 거예요.",
  "My mother is going to rest her back.": "엄마는 허리를 쉴 거예요.",
  "The child is going to turn his head.": "그 아이는 고개를 돌릴 거예요.",
  "Our teacher is going to point to her ears.": "우리 선생님은 자신의 귀를 가리킬 거예요.",
  "We study hard because we have a test today.": "오늘 시험이 있어서 우리는 열심히 공부해요.",
  "The classroom is big but the library is small.": "교실은 크지만 도서관은 작아요.",
  "She has a pencil and he has an eraser.": "그녀에게는 연필이 있고 그에게는 지우개가 있어요.",
  "Our class is busy because we have a project.": "우리는 해야 할 과제가 있어서 바빠요.",
  "He likes math but his sister likes English.": "그는 수학을 좋아하지만 그의 여자 형제는 영어를 좋아해요.",
  "The bell rings and the students go inside.": "종이 울리면 학생들이 안으로 들어가요.",
  "Lunch is ready but we must wait for our teacher.": "점심은 준비되었지만 우리는 선생님을 기다려야 해요.",
  "They clean the room and put away their books.": "그들은 방을 청소하고 책을 제자리에 정리해요.",
  "You need paper because we will draw a picture.": "우리가 그림을 그릴 거라서 종이가 필요해요.",
  "The lesson is short but everyone learns a lot.": "수업은 짧지만 모두 많은 것을 배워요.",
  "I want to be a farmer and work in spring.": "나는 농부가 되어 봄에 일하고 싶어요.",
  "My dream is to be a swimmer in summer.": "내 꿈은 여름에 수영 선수가 되는 거예요.",
  "She wants to be a weather reporter someday.": "그녀는 언젠가 날씨를 알려 주는 사람이 되고 싶어 해요.",
  "He hopes to be a park worker in the fall.": "그는 가을에 공원에서 일하는 사람이 되고 싶어 해요.",
  "Winter makes me want to be a ski teacher.": "겨울이 되면 나는 스키 선생님이 되고 싶어요.",
  "In spring, I want to be a flower shop owner.": "봄에는 꽃집 주인이 되고 싶어요.",
  "Summer makes her want to be a lifeguard.": "여름이 되면 그녀는 물놀이 안전을 지키는 사람이 되고 싶어 해요.",
  "In the fall, he wants to be a photographer.": "그는 가을에 사진작가가 되고 싶어 해요.",
  "Cold days make me want to be a baker.": "추운 날에는 빵을 만드는 사람이 되고 싶어요.",
  "Warm weather makes us want to be gardeners.": "날씨가 따뜻하면 우리는 정원을 가꾸는 사람이 되고 싶어요.",
  "Let's wear our new shirts today.": "오늘 새 셔츠를 입어요.",
  "How about putting on this blue jacket?": "이 파란색 재킷을 입어 보는 게 어때요?",
  "Why don't you try the red dress?": "빨간색 원피스를 입어 보는 게 어때요?",
  "Let's choose a hat for your brother.": "네 남자 형제의 모자를 골라 봐요.",
  "How about wearing these black pants?": "이 검은색 바지를 입어 보는 게 어때요?",
  "Why don't we buy a warm coat for winter?": "겨울에 입을 따뜻한 코트를 사는 게 어때요?",
  "Let's put on our socks before we go out.": "밖에 나가기 전에 양말을 신어요.",
  "How about trying this yellow skirt?": "이 노란색 치마를 입어 보는 게 어때요?",
  "Why don't you wear your white shoes?": "흰 신발을 신는 게 어때요?",
  "Let's find a clean sweater for your sister.": "네 여자 형제가 입을 깨끗한 스웨터를 찾아봐요.",
  "A mother is a woman who has a child.": "어머니는 아이를 둔 여자예요.",
  "A father is a man who has a child.": "아버지는 아이를 둔 남자예요.",
  "A sister is a girl in your family.": "자매는 가족 중 여자 형제예요.",
  "A brother is a boy in your family.": "형제는 가족 중 남자 형제예요.",
  "A grandmother is the mother of your parent.": "할머니는 부모님의 어머니예요.",
  "A grandfather is the father of your parent.": "할아버지는 부모님의 아버지예요.",
  "A baby is a very young child.": "아기는 아주 어린 아이예요.",
  "A daughter is a girl who is someone's child.": "딸은 부모에게 여자아이인 자녀예요.",
  "A son is a boy who is someone's child.": "아들은 부모에게 남자아이인 자녀예요.",
  "Children are the sons and daughters in a family.": "자녀는 가족의 아들과 딸이에요.",
  "Soccer is more popular than tennis in our class.": "우리 반에서는 축구가 테니스보다 더 인기가 많아요.",
  "Basketball uses a bigger ball than baseball.": "농구는 야구보다 더 큰 공을 사용해요.",
  "Running is easier for me than swimming.": "나는 달리기가 수영보다 더 쉬워요.",
  "Table tennis needs a smaller ball than golf.": "탁구는 골프보다 더 작은 공을 사용해요.",
  "Baseball games are longer than our soccer games.": "야구 경기는 우리 축구 경기보다 더 오래 해요.",
  "Swimming is harder for me than skating.": "나는 수영이 스케이트보다 더 어려워요.",
  "Volleyball has a higher net than tennis.": "배구는 테니스보다 그물이 더 높아요.",
  "Golf is slower for me than basketball.": "나는 골프가 농구보다 더 느리게 느껴져요.",
  "Cycling feels faster than walking.": "자전거 타기는 걷기보다 더 빠르게 느껴져요.",
  "Skiing is more exciting for me than bowling.": "나는 스키가 볼링보다 더 신나요.",
  "The new toy makes him joyful.": "새 장난감 때문에 그는 기뻐해요.",
  "She is excited about her doll.": "그녀는 자기 인형 때문에 신이 났어요.",
  "He feels proud of his train.": "그는 자기 기차 장난감이 자랑스러워요.",
  "Playing with blocks is fun.": "블록을 가지고 노는 것은 재미있어요.",
  "Her teddy bear makes her calm.": "곰 인형은 그녀의 마음을 편안하게 해 줘요.",
  "They are upset about the broken kite.": "그들은 망가진 연 때문에 속상해요.",
  "This ball makes you cheerful.": "이 공은 너를 즐겁게 해 줘요.",
  "The puzzle makes my friend curious.": "그 퍼즐 때문에 내 친구는 궁금해해요.",
  "His car brings a big smile.": "그의 자동차 장난감은 그를 활짝 웃게 해요.",
  "Those cards make children interested.": "저 카드들은 아이들의 관심을 끌어요.",
  "She shares her sweet fruit with me.": "그녀는 달콤한 과일을 나와 나누어 먹어요.",
  "My kind classmates always help each other.": "우리 반의 친절한 친구들은 항상 서로 도와요.",
  "Can you keep this little secret?": "이 작은 비밀을 지켜 줄 수 있나요?",
  "We play funny board games together.": "우리는 함께 재미있는 보드게임을 해요.",
  "They walked side by side after school.": "그들은 방과 후에 나란히 걸었어요.",
  "I wrote a nice thank-you card for him.": "나는 그에게 멋진 감사 카드를 써 주었어요.",
  "Listening carefully shows true respect.": "잘 들어 주는 것은 상대를 존중하는 마음을 보여 줘요.",
  "Who wants to join our jump rope team?": "누가 우리 줄넘기 팀에 들어오고 싶나요?",
  "Good partners practice dancing every day.": "좋은 짝은 매일 함께 춤을 연습해요.",
  "Please cheer up when trouble comes.": "힘든 일이 생겨도 힘내세요.",
  "quite": "꽤",
  "glass": "유리",
  "bored": "지루한",
  "snowball": "눈덩이",
  "snowman": "눈사람",
  "sunshine": "햇빛",
  "raincoat": "비옷",
  "waterfall": "폭포",
  "sunflower": "해바라기",
  "snowflake": "눈송이",
  "firefly": "반딧불이",
  "greenhouse": "온실",
  "clothes": "옷",
  "sweater": "스웨터",
  "sneakers": "운동화",
  "trousers": "바지",
  "uniform": "제복",
  "pajamas": "잠옷",
  "gloves": "장갑",
  "boots": "부츠",
  "kindly": "친절하게",
  "happily": "행복하게",
  "sadly": "슬프게",
  "quietly": "조용히",
  "loudly": "큰 소리로",
  "carefully": "조심스럽게",
  "easily": "쉽게",
  "really": "정말",
  "usually": "보통",
  "slowly": "천천히",
  "We play soccer after school.": "우리는 방과 후에 축구를 해요.",
  "Do you like baseball?": "너는 야구를 좋아하니?",
  "My team practices every Friday.": "우리 팀은 금요일마다 연습해요.",
  "Can she play basketball well?": "그녀는 농구를 잘할 수 있나요?",
  "They run around the field.": "그들은 운동장을 뛰어다녀요.",
  "Our coach has a new ball.": "우리 코치 선생님에게 새 공이 있어요.",
  "I enjoy swimming with my friends.": "나는 친구들과 수영하는 것을 좋아해요.",
  "What sport do you like best?": "너는 어떤 운동을 가장 좋아하니?",
  "He can jump very high!": "그는 아주 높이 뛸 수 있어요!",
  "The game starts on Saturday.": "경기는 토요일에 시작해요.",
  "Mina said, “I like this doll.”": "미나는 “나는 이 인형이 좋아.”라고 말했어요.",
  "Joon said, “My robot is new.”": "준은 “내 로봇은 새것이야.”라고 말했어요.",
  "Sora said, “This puzzle is fun.”": "소라는 “이 퍼즐은 재미있어.”라고 말했어요.",
  "Jun said, “Can I use your top?”": "준은 “네 팽이를 써도 될까?”라고 말했어요.",
  "Bora said, “Do you want this game?”": "보라는 “이 게임 갖고 싶니?”라고 말했어요.",
  "She said, “This doll is cute.”": "그녀는 “이 인형은 귀여워.”라고 말했어요.",
  "He said, “My robot can walk.”": "그는 “내 로봇은 걸을 수 있어.”라고 말했어요.",
  "I said, “That ball is mine.”": "나는 “저 공은 내 거야.”라고 말했어요.",
  "Mom said, “Put the blocks away.”": "엄마는 “블록을 정리해.”라고 말했어요.",
  "Dad said, “The kite is very high.”": "아빠는 “연이 아주 높이 떠 있어.”라고 말했어요.",
  "Meet your friends by the gate.": "문 옆에서 친구들을 만나세요.",
  "Please wait for us after class.": "수업이 끝난 뒤에 우리를 기다려 주세요.",
  "Come to my house this afternoon.": "오늘 오후에 우리 집에 오세요.",
  "Bring a snack for our picnic.": "우리 소풍에 먹을 간식을 가져오세요.",
  "We can play games in the park.": "우리는 공원에서 게임을 할 수 있어요.",
  "Call me when you get home.": "집에 도착하면 나에게 전화해 주세요.",
  "Share these cookies with your team.": "이 쿠키를 팀 친구들과 나눠 먹으세요.",
  "Sit next to your best friend.": "가장 친한 친구 옆에 앉으세요.",
  "Join our club after school.": "방과 후에 우리 동아리에 들어오세요.",
  "Help each other with this work.": "이 일을 서로 도와주세요.",
  "Thank you for playing chess with me.": "나와 체스를 해 줘서 고마워요.",
  "I'm sorry I lost your soccer ball.": "네 축구공을 잃어버려서 미안해요.",
  "Thanks for teaching me this song.": "이 노래를 가르쳐 줘서 고마워요.",
  "Thank you for reading my story.": "내 이야기를 읽어 줘서 고마워요.",
  "Sorry, I forgot our dance practice.": "미안해요, 우리 춤 연습을 깜빡했어요.",
  "Thanks for showing me how to swim.": "수영하는 법을 알려 줘서 고마워요.",
  "I'm sorry I missed the music club.": "음악 동아리에 못 가서 미안해요.",
  "Thank you for taking my picture.": "내 사진을 찍어 줘서 고마워요.",
  "Sorry, I can't join the basketball game.": "미안해요, 농구 경기에 함께할 수 없어요.",
  "Thanks for helping with my drawing.": "내 그림을 도와줘서 고마워요.",
  "Would you like to hear my new song?": "내 새 노래를 들어 볼래요?",
  "Come and sing with us after school.": "방과 후에 와서 우리와 함께 노래해요.",
  "Let's meet for band practice tomorrow.": "내일 밴드 연습을 하러 만나요.",
  "Can you join our music club this Friday?": "이번 금요일에 우리 음악 동아리에 올 수 있나요?",
  "Please come to the piano show tonight.": "오늘 밤 피아노 공연에 와 주세요.",
  "How about playing the guitar together?": "함께 기타를 치는 게 어때요?",
  "I promise to bring my drum next time.": "다음에는 꼭 내 북을 가져올게요.",
  "We can listen to your favorite songs later.": "나중에 네가 좋아하는 노래를 들을 수 있어요.",
  "Join me for a dance class this afternoon.": "오늘 오후에 나와 함께 춤 수업에 가요.",
  "I'll practice the flute before our show.": "우리 공연 전에 플루트를 연습할게요.",
  "The dog is hungry, so give it some food.": "개가 배고파하니 먹이를 좀 주세요.",
  "My cat is cold, so I put it inside.": "고양이가 추워해서 집 안으로 데려왔어요.",
  "This bird can't fly, so we should help it.": "이 새는 날지 못하니 우리가 도와줘야 해요.",
  "The rabbit is thirsty, so bring some water.": "토끼가 목말라하니 물을 좀 가져오세요.",
  "A fish looks sick, so tell an adult.": "물고기가 아파 보이니 어른에게 말하세요.",
  "The horse is tired, so let it rest.": "말이 지쳤으니 쉬게 해 주세요.",
  "That duck is lost, so look for its home.": "저 오리가 길을 잃었으니 집을 찾아 주세요.",
  "Our puppy is dirty, so wash it gently.": "우리 강아지가 더러우니 살살 씻겨 주세요.",
  "The turtle is in danger, so move it away.": "거북이가 위험하니 안전한 곳으로 옮겨 주세요.",
  "A small frog is stuck, so set it free.": "작은 개구리가 갇혔으니 풀어 주세요.",
  "My family ate dinner together.": "우리 가족은 함께 저녁을 먹었어요.",
  "Dad opened the window slowly.": "아빠는 창문을 천천히 열었어요.",
  "Mom found a note by her bed.": "엄마는 침대 옆에서 쪽지를 발견했어요.",
  "Our puppy waited near the door.": "우리 강아지는 문 근처에서 기다렸어요.",
  "Grandma baked bread that morning.": "할머니는 그날 아침 빵을 구웠어요.",
  "I heard a sound from upstairs.": "나는 위층에서 나는 소리를 들었어요.",
  "Someone knocked before breakfast.": "아침을 먹기 전에 누군가 문을 두드렸어요.",
  "The kitchen light was still on.": "부엌 불이 아직 켜져 있었어요.",
  "A little bird flew into my room.": "작은 새 한 마리가 내 방으로 날아왔어요.",
  "We looked for the missing key.": "우리는 사라진 열쇠를 찾았어요.",
  "This is a peaceful forest with tall green trees.": "이곳은 키 큰 푸른 나무가 있는 평화로운 숲이에요.",
  "Look at this deep lake between high mountains.": "높은 산들 사이에 있는 이 깊은 호수를 보세요.",
  "Here is a wide river where ducks swim together.": "이곳은 오리들이 함께 헤엄치는 넓은 강이에요.",
  "Meet the park ranger who protects wild animals.": "야생 동물을 지키는 공원 관리인을 만나 보세요.",
  "That is our sunny campsite near the quiet ocean.": "저곳은 조용한 바다 근처에 있는 햇살 좋은 야영장이에요.",
  "Welcome to the island that has lovely flowers.": "예쁜 꽃이 피어 있는 섬에 온 것을 환영해요.",
  "This spot is a warm valley full of fresh fruit.": "이곳은 싱싱한 과일이 가득한 따뜻한 골짜기예요.",
  "Come see the bright garden by the small hill.": "작은 언덕 옆에 있는 밝은 정원을 보러 오세요.",
  "That brave guide shows visitors around the cave.": "저 용감한 안내원은 사람들에게 동굴을 구경시켜 줘요.",
  "Here is an open beach with clean yellow sand.": "이곳은 깨끗한 노란 모래가 펼쳐진 넓은 해변이에요.",
  "I think warm vegetable soup is healthy.": "나는 따뜻한 채소 수프가 몸에 좋다고 생각해요.",
  "In my opinion, sweet melon tastes delicious.": "내 생각에는 달콤한 멜론이 맛있어요.",
  "Eating fresh fruit every day is very important.": "매일 신선한 과일을 먹는 것은 아주 중요해요.",
  "My view is that spicy noodles are too hot.": "내 생각에는 매운 국수가 너무 매워요.",
  "From my point of view, baking bread is fun.": "내 생각에는 빵을 굽는 것이 재미있어요.",
  "To me, cold milk is better than sweet soda.": "나는 달콤한 탄산음료보다 차가운 우유가 더 좋아요.",
  "I feel that green salad makes a good lunch.": "나는 초록 채소 샐러드가 점심으로 좋다고 생각해요.",
  "We should eat less salty food for our body.": "우리 몸을 위해 짠 음식을 적게 먹어야 해요.",
  "It seems to me that breakfast gives us energy.": "나는 아침밥을 먹으면 힘이 난다고 생각해요.",
  "You might think fried chicken is too oily.": "너는 치킨이 너무 기름지다고 생각할 수도 있어요.",
  "Turn left at the bank and go straight.": "은행에서 왼쪽으로 돌고 곧장 가세요.",
  "There is a bakery, but it is closed today.": "빵집이 있지만 오늘은 문을 닫았어요.",
  "I like my neighborhood because it is quiet.": "우리 동네는 조용해서 좋아요.",
  "Go past the market and look for the library.": "시장을 지나서 도서관을 찾아보세요.",
  "We visited the museum, and it was so big.": "우리는 박물관에 갔는데 정말 컸어요.",
  "Walk two blocks, then you will see the post office.": "두 블록을 걸어가면 우체국이 보여요.",
  "Cross the busy street, but be very careful.": "차가 많은 길을 건너되 아주 조심하세요.",
  "The park is nearby, so many children play there.": "공원이 가까워서 많은 아이들이 그곳에서 놀아요.",
  "Where is the police station, and is it far away?": "경찰서는 어디에 있고, 여기서 먼가요?",
  "I stopped by the bookstore to buy some comic books.": "나는 만화책을 사려고 서점에 들렀어요.",
  "I feel happy today.": "나는 오늘 기분이 좋아요.",
  "She was angry yesterday.": "그녀는 어제 화가 났어요.",
  "Are you bored now?": "지금 지루하니?",
  "We feel proud of him.": "우리는 그가 자랑스러워요.",
  "He looks very tired.": "그는 아주 피곤해 보여요.",
  "They felt excited.": "그들은 신이 났어요.",
  "She is worried about it.": "그녀는 그것을 걱정하고 있어요.",
  "The boy was surprised.": "그 소년은 놀랐어요.",
  "I felt upset then.": "나는 그때 속상했어요.",
  "Is he nervous now?": "그는 지금 긴장하고 있나요?",
  "My cat has black feet.": "내 고양이는 발이 검은색이에요.",
  "Put this block on the desk.": "이 블록을 책상 위에 놓으세요.",
  "Do you like brown bread?": "갈색 빵을 좋아하니?",
  "Who is wearing the small crown?": "누가 작은 왕관을 쓰고 있나요?",
  "We need some glue for this box.": "이 상자에는 풀이 좀 필요해요.",
  "These green apples taste good.": "이 초록색 사과들은 맛이 좋아요.",
  "Let's greet our new teacher.": "새로 오신 선생님께 인사해요.",
  "There is a white bird outside.": "밖에 흰 새 한 마리가 있어요.",
  "Can you write your name here?": "여기에 네 이름을 쓸 수 있니?",
  "I have a green bag.": "나는 초록색 가방이 있어요.",
  "The airplane is flying above the clouds.": "비행기가 구름 위를 날고 있어요.",
  "Put your lunch in the backpack.": "점심을 가방에 넣으세요.",
  "A long railroad connects the two towns.": "긴 철길이 두 마을을 이어 줘요.",
  "Where is my passport?": "내 여권은 어디에 있나요?",
  "We played games by the seaside yesterday.": "우리는 어제 바닷가에서 게임을 했어요.",
  "Thank you for the beautiful postcard!": "예쁜 엽서를 줘서 고마워요!",
  "This suitcase is too heavy for me.": "이 여행 가방은 내가 들기에 너무 무거워요.",
  "There are many buses on the highway.": "큰 도로에 버스가 많이 있어요.",
  "Can we take the subway home?": "우리 집에 지하철을 타고 가도 될까요?",
  "My dad will meet us at the airport.": "우리 아빠가 공항에서 우리를 만날 거예요.",
  "Let us exercise in the park.": "공원에서 운동해요.",
  "Did you eat breakfast today?": "오늘 아침을 먹었니?",
  "Please finish your homework before bed.": "자기 전에 숙제를 끝내세요.",
  "The bus schedule is on the wall.": "버스 시간표가 벽에 있어요.",
  "There is a calendar by the door.": "문 옆에 달력이 있어요.",
  "We need to practice this song.": "우리는 이 노래를 연습해야 해요.",
  "What would you like for dinner?": "저녁으로 무엇을 먹고 싶나요?",
  "I walk to school every morning.": "나는 매일 아침 걸어서 학교에 가요.",
  "How beautiful the sky looks this evening!": "오늘 저녁 하늘이 정말 아름다워요!",
  "I eat breakfast with my family.": "나는 가족과 함께 아침을 먹어요.",
  "Dress warmly before you go outside.": "밖에 나가기 전에 따뜻하게 입으세요.",
  "The moon is shining brightly tonight.": "오늘 밤 달이 밝게 빛나고 있어요.",
  "The wind blew strongly all night.": "밤새 바람이 세게 불었어요.",
  "Snow fell lightly on the trees.": "나무 위에 눈이 살짝 내렸어요.",
  "Suddenly, dark clouds covered the sky.": "갑자기 검은 구름이 하늘을 덮었어요.",
  "Please close the window gently.": "창문을 살며시 닫아 주세요.",
  "My feet hurt badly after the walk.": "걷고 나니 발이 많이 아팠어요.",
  "We can finally have a picnic!": "드디어 소풍을 갈 수 있어요!",
  "Why did the rain start so early?": "왜 비가 이렇게 일찍 내리기 시작했나요?",
  "It is nearly time to go swimming.": "이제 곧 수영하러 갈 시간이에요.",
  "My left hand feels cold.": "내 왼손이 차가워요.",
  "Can you touch your toes?": "발가락을 만질 수 있나요?",
  "She has long brown hair.": "그녀는 긴 갈색 머리예요.",
  "Please wash your hands well.": "손을 깨끗이 씻으세요.",
  "His right knee hurts today.": "그는 오늘 오른쪽 무릎이 아파요.",
  "Do your eyes feel tired?": "눈이 피곤한가요?",
  "We use our ears to hear sounds.": "우리는 귀로 소리를 들어요.",
  "Open your mouth and say ah.": "입을 벌리고 아 하고 말하세요.",
  "Her face looks very happy.": "그녀의 얼굴이 아주 행복해 보여요.",
  "I brush my teeth every morning.": "나는 매일 아침 이를 닦아요.",
  "Mina said, “I go to school early.”": "미나는 “나는 일찍 학교에 가.”라고 말했어요.",
  "Joon said, “Our classroom is clean.”": "준은 “우리 교실은 깨끗해.”라고 말했어요.",
  "Sora said, “My book is on the desk.”": "소라는 “내 책은 책상 위에 있어.”라고 말했어요.",
  "Jun said, “Where is the music room?”": "준은 “음악실이 어디에 있어?”라고 말했어요.",
  "Bora said, “Do you have an eraser?”": "보라는 “지우개가 있니?”라고 말했어요.",
  "My teacher said, “Open your book.”": "선생님은 “책을 펴세요.”라고 말했어요.",
  "She said, “Please sit down.”": "그녀는 “앉아 주세요.”라고 말했어요.",
  "He asked, “Where is my pencil?”": "그는 “내 연필이 어디에 있지?”라고 물었어요.",
  "My friend said, “This is my desk.”": "내 친구는 “이건 내 책상이야.”라고 말했어요.",
  "The teacher said, “Write your name.”": "선생님은 “이름을 쓰세요.”라고 말했어요.",
  "Spring begins with warm days.": "봄이 되면 날씨가 따뜻해지기 시작해요.",
  "Summer weather is often hot.": "여름에는 날씨가 자주 더워요.",
  "Fall brings cool air and colorful leaves.": "가을에는 날씨가 선선해지고 나뭇잎이 여러 색으로 물들어요.",
  "Winter nights can be very cold.": "겨울밤은 아주 추울 수 있어요.",
  "Flowers grow well during spring.": "꽃은 봄에 잘 자라요.",
  "Wear light clothes on hot summer days.": "더운 여름날에는 얇은 옷을 입으세요.",
  "Many leaves turn yellow in fall.": "가을에는 많은 나뭇잎이 노랗게 변해요.",
  "Put on a coat before going outside.": "밖에 나가기 전에 외투를 입으세요.",
  "Snow may cover the ground in winter.": "겨울에는 눈이 땅을 덮을 수도 있어요.",
  "Enjoy fresh fruit during summer.": "여름에는 신선한 과일을 맛있게 먹어요.",
  "Thank you for finding my jacket.": "내 재킷을 찾아 줘서 고마워요.",
  "I'm sorry I took your hat by mistake.": "실수로 네 모자를 가져가서 미안해요.",
  "Thanks for washing these socks.": "이 양말을 빨아 줘서 고마워요.",
  "I'm sorry I got your shirt wet.": "네 셔츠를 젖게 해서 미안해요.",
  "Thank you for lending me your coat.": "네 외투를 빌려줘서 고마워요.",
  "Sorry, I forgot to bring your skirt.": "미안해요, 네 치마를 가져오는 걸 깜빡했어요.",
  "Thanks for picking up my gloves.": "내 장갑을 주워 줘서 고마워요.",
  "I'm sorry I stepped on your shoes.": "네 신발을 밟아서 미안해요.",
  "Thank you for fixing this button.": "이 단추를 고쳐 줘서 고마워요.",
  "Sorry, I can't find your blue pants.": "미안해요, 네 파란 바지를 찾을 수 없어요.",
  "Will you visit my family on Sunday?": "일요일에 우리 가족을 만나러 올래요?",
  "Please have dinner with my parents.": "우리 부모님과 함께 저녁을 먹어요.",
  "How about coming to our house tomorrow?": "내일 우리 집에 오는 게 어때요?",
  "Dad will take us to the park this weekend.": "이번 주말에 아빠가 우리를 공원에 데려갈 거예요.",
  "Mom says you can stay for lunch.": "엄마가 점심을 먹고 가도 된다고 하셨어요.",
  "My sister wants to invite you home.": "내 여동생은 너를 우리 집에 초대하고 싶어 해요.",
  "I'll help Grandma cook in the morning.": "나는 아침에 할머니의 요리를 도와드릴 거예요.",
  "Can your brother come over after class?": "네 남자 형제가 수업 후에 우리 집에 올 수 있나요?",
  "Our family will meet at five o'clock.": "우리 가족은 다섯 시에 만날 거예요.",
  "I promise to call Grandpa this evening.": "오늘 저녁에 꼭 할아버지께 전화할게요.",
  "I can't kick well, so I'll practice more.": "나는 공을 잘 차지 못해서 더 연습할 거예요.",
  "My tennis ball is gone, so I'll get another.": "내 테니스공이 없어져서 다른 공을 가져올 거예요.",
  "We are losing, but let's keep trying.": "우리가 지고 있지만 계속 힘내 봐요.",
  "He fell during soccer, so let him sit down.": "그가 축구를 하다가 넘어졌으니 앉아서 쉬게 해 주세요.",
  "She can't swim yet, so teach her slowly.": "그녀는 아직 수영을 못하니 천천히 가르쳐 주세요.",
  "The bat is broken, so use a different one.": "방망이가 부러졌으니 다른 것을 쓰세요.",
  "Our team is late, so let's run to the field.": "우리 팀이 늦었으니 운동장으로 뛰어가요.",
  "I feel tired, so I'll take a short break.": "피곤해서 잠깐 쉴 거예요.",
  "The court is wet, so wait until it is dry.": "경기장이 젖었으니 마를 때까지 기다리세요.",
  "My bike has a problem, so I'll walk today.": "내 자전거에 문제가 있어서 오늘은 걸어갈 거예요.",
  "His robot walked across the floor.": "그의 로봇이 바닥을 가로질러 걸어갔어요.",
  "She picked up a shiny ball.": "그녀는 반짝이는 공을 주웠어요.",
  "That doll wore a pretty hat.": "저 인형은 예쁜 모자를 쓰고 있었어요.",
  "Three blocks fell off the table.": "블록 세 개가 책상에서 떨어졌어요.",
  "Ben pushed his toy car forward.": "벤은 장난감 자동차를 앞으로 밀었어요.",
  "An old kite rose above the trees.": "낡은 연 하나가 나무 위로 높이 올라갔어요.",
  "Two bears sat inside a small box.": "곰 두 마리가 작은 상자 안에 앉아 있었어요.",
  "Her train stopped beside the bridge.": "그녀의 기차가 다리 옆에 멈췄어요.",
  "This plane made a funny noise.": "이 비행기는 재미있는 소리를 냈어요.",
  "One puzzle piece could not be found.": "퍼즐 조각 하나를 찾을 수 없었어요.",
  "Meet my kind classmate who always helps others.": "항상 다른 사람을 도와주는 친절한 우리 반 친구를 만나 보세요.",
  "This is our classroom where we study science.": "이곳은 우리가 과학을 공부하는 교실이에요.",
  "Here is the library where friends read stories.": "이곳은 친구들이 이야기를 읽는 도서관이에요.",
  "She is my best friend from the art club.": "그녀는 미술 동아리에서 만난 가장 친한 친구예요.",
  "Welcome to our playground beside the big gym.": "큰 체육관 옆에 있는 우리 운동장에 온 것을 환영해요.",
  "Look at this computer room where partners talk.": "짝과 함께 이야기하는 이 컴퓨터실을 보세요.",
  "Meet Bora, who shares her cute notebooks happily.": "예쁜 공책을 즐겁게 나누어 주는 보라를 만나 보세요.",
  "This quiet place is our favorite school bench.": "이 조용한 곳은 우리가 가장 좋아하는 학교 벤치예요.",
  "He is an honest leader who listens to everyone.": "그는 모든 사람의 말을 잘 들어주는 정직한 지도자예요.",
  "Come see our colorful art room down the hall.": "복도 안쪽에 있는 알록달록한 우리 미술실을 보러 오세요.",
  "I think taking photos of cats is exciting.": "나는 고양이 사진을 찍는 것이 신난다고 생각해요.",
  "In my view, swimming after school builds power.": "내 생각에는 방과 후에 수영하면 힘이 길러져요.",
  "Learning guitar seems quite challenging to me.": "나는 기타를 배우는 것이 꽤 어렵게 느껴져요.",
  "My thought is that dancing keeps us cheerful.": "내 생각에는 춤을 추면 즐거운 기분이 들어요.",
  "To my mind, riding a bicycle feels wonderful.": "내 생각에는 자전거를 타는 것이 정말 좋아요.",
  "I believe playing board games brings great joy.": "나는 보드게임을 하면 무척 즐겁다고 생각해요.",
  "Camping with family can be a fantastic hobby.": "가족과 캠핑하는 것은 아주 멋진 취미가 될 수 있어요.",
  "It feels like flying kites brings peaceful rest.": "연을 날리면 마음이 편안해지는 것 같아요.",
  "You will find that planting seeds teaches care.": "씨앗을 심으면 잘 돌보는 법을 배울 수 있어요.",
  "Collecting coins appears very interesting.": "동전을 모으는 것은 아주 재미있어 보여요.",
  "She can sing very well, and she plays the piano.": "그녀는 노래를 아주 잘하고 피아노도 쳐요.",
  "I wanted to join the band, but I was nervous.": "나는 밴드에 들어가고 싶었지만 긴장했어요.",
  "Listen to this cheerful sound and tap your feet.": "이 즐거운 소리를 들으며 발로 박자를 맞춰 보세요.",
  "We practiced together because the concert is soon.": "공연이 얼마 남지 않아서 우리는 함께 연습했어요.",
  "Do you like classical music, or do you prefer rock?": "클래식 음악을 좋아하나요, 아니면 록 음악을 더 좋아하나요?",
  "The flute is small, but it makes a sweet melody.": "플루트는 작지만 아름다운 가락을 들려줘요.",
  "They formed a team, and everyone played the drums.": "그들은 팀을 만들었고 모두 북을 연주했어요.",
  "Sing the whole song loudly, and smile at people.": "노래를 처음부터 끝까지 큰 소리로 부르며 사람들에게 웃어 주세요.",
  "I enjoy quiet jazz, while my sister loves pop songs.": "나는 잔잔한 재즈를 좋아하고 내 여동생은 팝송을 좋아해요.",
  "He plays the violin every day to prepare for it.": "그는 그것을 준비하려고 매일 바이올린을 연주해요.",
  "The bear runs fast.": "곰은 빠르게 달려요.",
  "A monkey climbs high.": "원숭이가 높은 곳까지 올라가요.",
  "Dolphins swim well.": "돌고래는 수영을 잘해요.",
  "Look at the tall giraffe.": "키가 큰 기린을 보세요.",
  "Elephants have long trunks.": "코끼리는 긴 코를 가지고 있어요.",
  "Tigers live in forests.": "호랑이는 숲에 살아요.",
  "The cute rabbit hops.": "귀여운 토끼가 깡충깡충 뛰어요.",
  "Whales are very large.": "고래는 아주 커요.",
  "A zebra eats green grass.": "얼룩말이 푸른 풀을 먹어요.",
  "Penguins cannot fly.": "펭귄은 날 수 없어요.",
};
